//! Raw Rust FFI bindings to the WAMR (WebAssembly Micro Runtime) C API.
//!
//! Generated by `bindgen` from `wasm_export.h` and `wasm_c_api.h`.
//! The committed bindings in `src/bindings.rs` are the canonical ones;
//! regenerate them with:
//!
//! ```sh
//! WAMR_BINDGEN_COMMIT=1 cargo build
//! ```

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

// When built with bindgen available, use the generated output.
// Otherwise, fall back to the committed snapshot.
#[cfg(feature = "regenerate")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(not(feature = "regenerate"))]
include!("bindings.rs");
