// Syncs the canonical wasm3 sources (src/vendors/wasm3) into the iOS Swift
// package, and the generated test fixtures into the platform test suites.
//
// SwiftPM requires a target's sources to live inside the package directory,
// so the iOS package carries a script-managed copy. The Android build
// compiles the canonical sources directly and needs no copy.
//
// Usage: node tools/sync-wasm3.mjs
import { cpSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const vendorDir = join(pkgRoot, 'src', 'vendors', 'wasm3');
const cTargetDir = join(pkgRoot, 'platforms', 'ios', 'NSCWasm3', 'Sources', 'CWasm3');
const fixturesDir = join(pkgRoot, 'test-support', 'fixtures');

// Public headers exposed to Swift via the SwiftPM include dir.
const publicHeaders = ['wasm3.h', 'wasm3_defs.h'];
// WASI/uvwasi backends are not used on mobile; keep the package lean.
const excluded = new Set(['m3_api_uvwasi.c', 'm3_api_meta_wasi.c', '.DS_Store']);

rmSync(cTargetDir, { recursive: true, force: true });
mkdirSync(join(cTargetDir, 'include'), { recursive: true });

let copied = 0;
for (const entry of readdirSync(vendorDir)) {
  if (excluded.has(entry)) continue;
  const dest = publicHeaders.includes(entry)
    ? join(cTargetDir, 'include', entry)
    : join(cTargetDir, entry);
  cpSync(join(vendorDir, entry), dest);
  copied++;
}
writeFileSync(
  join(cTargetDir, 'README.md'),
  '<!-- GENERATED by tools/sync-wasm3.mjs — do not edit. Canonical sources: src/vendors/wasm3 -->\n',
);
console.log(`synced ${copied} wasm3 files -> ${cTargetDir}`);

// Fixtures for the Swift test target and the Android host tests.
const targets = [
  join(pkgRoot, 'platforms', 'ios', 'NSCWasm3', 'Tests', 'NSCWasm3Tests', 'Fixtures'),
  join(pkgRoot, 'platforms', 'android', 'wasm3-android', 'hosttest', 'src', 'test', 'resources', 'fixtures'),
];
for (const dir of targets) {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  for (const f of readdirSync(fixturesDir)) cpSync(join(fixturesDir, f), join(dir, f));
  console.log(`synced fixtures -> ${dir}`);
}
