import { rspack } from '@rspack/core'
import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import { extname, relative, resolve } from 'node:path'
import postcssImport from 'postcss-import'
import type { RspackChain } from 'rspack-chain'
import { getEnv, type INativeScriptRspackEnv } from '../env.js'
import { getValue } from '../helpers/config.js'
import { addCopyRule, applyCopyRules } from '../helpers/copy-rules.js'
import {
    getDependencyVersion,
    getResolvedDependencyVersionForCheck,
    hasDependency,
} from '../helpers/dependencies.js'
import { applyDotEnvPlugin } from '../helpers/dot-env.js'
import { applyFileReplacements } from '../helpers/file-replacements.js'
import { getIPS } from '../helpers/host.js'
import { warnOnce } from '../helpers/log.js'
import {
    getAbsoluteDistPath,
    getEntryDirPath,
    getEntryPath,
    getPlatformName,
} from '../helpers/platform.js'
import { getProjectFilePath } from '../helpers/project.js'
import { isVersionGte } from '../helpers/version.js'
import { WatchStatePlugin } from '../plugins/watch-state-plugin.js'
import { ownAsset, ownLoader, vendorLoader } from './paths.js'

const require = createRequire(import.meta.url)

/**
 * The NativeScript base configuration, expressed directly against rspack.
 *
 * This is a port of `@nativescript/webpack`'s base config; the webpack-only
 * pieces are gone rather than adapted:
 *  - `ts-loader` → `builtin:swc-loader` (ts-loader drives the webpack
 *    NormalModule API rspack does not implement)
 *  - `fork-ts-checker-webpack-plugin` → the project's own `typecheck` task
 *  - `terser-webpack-plugin` → rspack's swc minimizer, configured to keep the
 *    function and class names the {N} runtimes reflect over
 *  - `PlatformSuffixPlugin` → `resolve.extensions` alone (see README)
 *  - `ContextExclusionPlugin` → the entry stub's own `require.context` filter
 *  - `copy-webpack-plugin` → `CopyRspackPlugin`
 *  - `dotenv-webpack` → `node:util`'s `parseEnv` + `DefinePlugin`
 */
export default function base(
    config: RspackChain,
    env: INativeScriptRspackEnv = getEnv(),
): RspackChain {
    const entryPath = getEntryPath()
    const platform = getPlatformName()
    const outputPath = getAbsoluteDistPath()
    const mode = env.production ? 'production' : 'development'

    config.mode(mode)

    // Inline source maps in development. Chrome DevTools cannot fetch
    // external .map files in this debugging flow (bundled DevTools blocks
    // http:// via CSP, the appspot frontend hits the same CSP, and the iOS V8
    // inspector backend fetch is blocked by App Transport Security). A `data:`
    // URL inlined in the bundle sidesteps all three.
    const defaultSourceMap = 'inline-source-map'

    // {N} 9 runtimes execute ESM; anything older needs CommonJS output.
    const runtimes = ['@nativescript/ios', '@nativescript/visionos', '@nativescript/android']

    const runtimeForPlatform: string | undefined = {
        android: '@nativescript/android',
        ios: '@nativescript/ios',
        visionos: '@nativescript/visionos',
    }[platform]

    if (runtimeForPlatform && runtimes.some((runtime) => hasDependency(runtime))) {
        const resolved =
            getResolvedDependencyVersionForCheck(runtimeForPlatform, '9.0.0') ??
            getDependencyVersion(runtimeForPlatform)

        if (!isVersionGte(resolved, '9.0.0')) {
            env.commonjs = true
        }
    } else if (runtimeForPlatform) {
        // no {N} runtime package at all — assume the oldest contract
        env.commonjs = true
    }

    if (env.hmr) {
        // the HMR runtime is CommonJS
        env.commonjs = true
    }

    // package.json is generated by the CLI with the runtime options in it, so
    // it is resolved on device rather than bundled
    config.externals(['package.json', '~/package.json'])

    // node builtins are not available on device and should be bundled from a
    // polyfill package (eg. `npm i url`) instead of being externalised
    config.set('externalsPresets', { node: false })

    config.resolve.merge({
        fallback: {
            module: ownAsset('polyfills/module.cjs'),
        },
        alias: {
            // css-tree tries to patch its data with mdn-data; it ships its own
            module: ownAsset('polyfills/module.cjs'),
            'mdn-data/css/properties.json': ownAsset('polyfills/empty-object.cjs'),
            'mdn-data/css/syntaxes.json': ownAsset('polyfills/empty-object.cjs'),
            'mdn-data/css/at-rules.json': ownAsset('polyfills/empty-object.cjs'),
        },
        // `../timer` has to keep resolving to `timer.<platform>.js`
        fullySpecified: false,
    })

    config.module
        .rule('esm-extensionless')
        .test(/\.(mjs|js|ts|tsx)$/)
        .resolve.set('fullySpecified', false)

    const getSourceMapType = (map: string | boolean | undefined): string | false => {
        if (typeof map === 'undefined') {
            // off in production unless --env.sourceMap=<type> asks for it
            return mode === 'production' ? false : defaultSourceMap
        }

        if (typeof map === 'boolean') {
            return map ? defaultSourceMap : false
        }

        return map
    }

    config.devtool(getSourceMapType(env.sourceMap) as never)

    // hidden-source-map writes the maps next to the platform folder instead of
    // into the app bundle
    if (env.sourceMap === 'hidden-source-map') {
        const sourceMapAbsolutePath = getProjectFilePath(
            `./${env.buildPath ?? 'platforms'}/${platform}-sourceMaps/[file].map[query]`,
        )

        config.output.sourceMapFilename(relative(outputPath, sourceMapAbsolutePath))
    }

    config.target('node')

    config
        .entry('bundle')
        // the {N} globals have to be installed before anything else runs
        .add('@nativescript/core/globals/index')
        .add('@nativescript/core/bundle-entry-points')
        .add(entryPath)

    if (platform === 'android') {
        // the static binding generator reads these out of the bundle to emit
        // the java classes
        const appComponents = Array.isArray(env.appComponents)
            ? [...env.appComponents]
            : env.appComponents
              ? [env.appComponents]
              : []

        appComponents.push('@nativescript/core/ui/frame', '@nativescript/core/ui/frame/activity')

        for (const component of appComponents) {
            config.entry('bundle').add(component)
        }
    }

    config.when(shouldIncludeInspectorModules(platform), (chain) => {
        chain.entry('tns_modules/inspector_modules').add('@nativescript/core/inspector_modules')
    })

    if (env.commonjs) {
        // No `libraryTarget`: rspack has no such option, and the {N} runtime
        // evaluates the entry chunk standalone rather than requiring it — the
        // `exports` shim in `finalizeChain` is what makes that work.
        config.output
            .path(outputPath)
            .pathinfo(false)
            .publicPath('')
            .globalObject('global')
            .set('clean', true)

        if (env.uniqueBundle) {
            config.output.filename(`[name].${env.uniqueBundle}.js`)
        }
    } else {
        config.merge({ experiments: { outputModule: true } })

        config.output
            .path(outputPath)
            .pathinfo(false)
            .publicPath('file:///app/')
            .set('module', true)
            .globalObject('global')
            .set('clean', true)

        if (env.uniqueBundle) {
            config.output.filename(`[name].${env.uniqueBundle}.mjs`)
        }

        // The {N} runtime provides import.meta itself; the bundler's
        // fileURLToPath() shims for __dirname/__filename import `node:url`,
        // which does not exist on device.
        config.node.set('__dirname', false)
        config.node.set('__filename', false)
    }

    config.watchOptions({
        ignored: [
            `${getProjectFilePath(env.buildPath ?? 'platforms')}/**`,
            `${getProjectFilePath(env.appResourcesPath ?? 'App_Resources')}/**`,
        ],
    })

    config.when(!!env.watchNodeModules, (chain) => {
        chain.set('snapshot', { managedPaths: [] })
    })

    // rspack minifies with swc. The {N} runtimes look native classes and
    // methods up by name, so names have to survive minification.
    config.optimization
        .minimizer('SwcJsMinimizerRspackPlugin')
        .use(rspack.SwcJsMinimizerRspackPlugin, [
            {
                minimizerOptions: {
                    compress: {
                        collapse_vars: platform !== 'android',
                        sequences: platform !== 'android',
                        keep_infinity: true,
                        keep_fnames: true,
                        keep_classnames: true,
                        drop_console: mode === 'production',
                        global_defs: { __UGLIFIED__: true },
                    },
                    mangle: { keep_fnames: true, keep_classnames: true },
                    format: { keepQuotedProps: true },
                },
            },
        ])

    config.optimization.runtimeChunk('single')

    if (env.commonjs) {
        config.optimization.splitChunks({
            cacheGroups: {
                defaultVendor: {
                    test: /[\\/]node_modules[\\/]/,
                    priority: -10,
                    name: 'vendor',
                    chunks: 'all',
                },
            },
        })
    } else {
        config.output.chunkFilename('[name].mjs')
        config.optimization.splitChunks({
            chunks: 'initial',
            cacheGroups: {
                default: false,
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendor',
                    chunks: 'initial',
                    priority: -10,
                    reuseExistingChunk: true,
                },
            },
        })
        config.optimization.set('moduleIds', 'named').set('chunkIds', 'named')
    }

    // this package's own loaders are referenced by absolute path; these search
    // paths only exist so plugin configs can keep naming loaders as strings
    config.resolveLoader.modules
        .add(ownAsset('loaders'))
        .add(getProjectFilePath('node_modules'))
        .add('node_modules')

    for (const extension of ['ts', 'js', 'mjs', 'css', 'scss', 'json']) {
        config.resolve.extensions.add(`.${platform}.${extension}`).add(`.${extension}`)
    }

    if (platform === 'visionos') {
        // visionOS reads .ios files too. The list has to be read out before
        // `clear()`, which empties the set the values come from.
        const extensions = config.resolve.extensions
            .values()
            .flatMap((ext) =>
                ext.includes('visionos') ? [ext, ext.replace('visionos', 'ios')] : [ext],
            )

        config.resolve.extensions.clear().merge(extensions)
    }

    config.resolve.alias.set('~', getEntryDirPath()).set('@', getEntryDirPath())
    config.resolve.symlinks(true)
    config.resolve.modules.add(getProjectFilePath('node_modules')).add('node_modules')

    config.module
        .rule('bundle')
        .enforce('post')
        .test(entryPath)
        .use('app-css-loader')
        .loader(ownLoader('app-css-loader'))
        .options({ platform })

    config.when(!!env.hmr, (chain) => {
        chain.module
            .rule('bundle')
            .use('nativescript-hot-loader')
            .loader(ownLoader('nativescript-hot-loader'))
            .options({ injectHMRRuntime: true })
    })

    config.when(!!env.profile, () => {
        warnOnce('profile', '--env.profile is not supported: rspack has no build profiler.')
    })

    config.module
        .rule('workers')
        .test(/\.(mjs|js|ts)$/)
        .use('nativescript-worker-loader')
        .loader(ownLoader('nativescript-worker-loader'))

    config.module
        .rule('ts')
        .test(/\.ts$/)
        // Loaders execute right-to-left, so the native-class pre-passes below
        // run before swc: strip → downlevel → swc.
        .use('swc-loader')
        .loader('builtin:swc-loader')
        .options({
            jsc: {
                parser: { syntax: 'typescript', decorators: true },
                // {N} projects rely on experimentalDecorators/emitDecoratorMetadata
                transform: { legacyDecorator: true, decoratorMetadata: true },
                target: 'es2020',
            },
        })
        .end()
        .use('native-class-downlevel-loader')
        .loader(ownLoader('native-class-downlevel-loader'))
        .end()
        .use('native-class-strip-loader')
        .loader(ownLoader('native-class-strip-loader'))

    config.module
        .rule('js')
        .test(/\.js$/)
        .exclude.add(/node_modules/)

    config.module
        .rule('xml')
        .test(/\.xml$/)
        .use('xml-namespace-loader')
        .loader(ownLoader('xml-namespace-loader'))

    // projects can still override all of this through postcss.config.js
    const postCSSOptions = {
        postcssOptions: {
            plugins: [
                postcssImport({
                    /**
                     * `@import "foo.css"` picks up `foo.ios.css` when it exists.
                     */
                    resolve(id: string, baseDir: string): string {
                        const targets = platform === 'visionos' ? [platform, 'ios'] : [platform]

                        for (const target of targets) {
                            const ext = extname(id)
                            const platformExt = ext ? `.${target}${ext}` : ''

                            if (!platformExt || id.includes(platformExt)) {
                                continue
                            }

                            const platformRequest = id.replace(ext, platformExt)

                            try {
                                return require.resolve(platformRequest, { paths: [baseDir] })
                            } catch {
                                // not a package request — try the file directly
                            }

                            const extPath = resolve(baseDir, platformRequest)

                            if (existsSync(extPath)) {
                                return extPath
                            }
                        }

                        return id
                    },
                }),
            ],
        },
    }

    config.module
        .rule('css')
        .test(/\.css$/)
        .use('apply-css-loader')
        .loader(ownLoader('apply-css-loader'))
        .end()
        .use('css2json-loader')
        .loader(ownLoader('css2json-loader'))
        .end()
        .use('postcss-loader')
        .loader(vendorLoader('postcss-loader'))
        .options(postCSSOptions)

    config.module
        .rule('scss')
        .test(/\.scss$/)
        .use('apply-css-loader')
        .loader(ownLoader('apply-css-loader'))
        .end()
        .use('css2json-loader')
        .loader(ownLoader('css2json-loader'))
        .end()
        .use('postcss-loader')
        .loader(vendorLoader('postcss-loader'))
        .options(postCSSOptions)
        .end()
        .use('sass-loader')
        .loader(vendorLoader('sass-loader'))
        .options({
            // workspaces often end up with several nested Sass implementations
            implementation: require.resolve('sass'),
        })

    config.set(
        'ignoreWarnings',
        ((config.get('ignoreWarnings') as unknown[] | undefined) ?? []).concat([
            /System.import\(\) is deprecated/,
        ]),
    )

    config.plugin('DefinePlugin').use(rspack.DefinePlugin, [
        {
            __DEV__: mode === 'development',
            __NS_WEBPACK__: true,
            __NS_ENV_VERBOSE__: !!env.verbose,
            __NS_DEV_HOST_IPS__: mode === 'development' ? JSON.stringify(getIPS()) : `[]`,
            __CSS_PARSER__: JSON.stringify(getValue('cssParser', 'css-tree')),
            __UI_USE_XML_PARSER__: true,
            __UI_USE_EXTERNAL_RENDERER__: false,
            __COMMONJS__: !!env.commonjs,
            __ANDROID__: platform === 'android',
            __IOS__: platform === 'ios',
            __VISIONOS__: platform === 'visionos',
            __APPLE__: platform === 'ios' || platform === 'visionos',
            /* for compat only */ 'global.isAndroid': platform === 'android',
            /* for compat only */ 'global.isIOS': platform === 'ios' || platform === 'visionos',
            /* for compat only */ 'global.isVisionOS': platform === 'visionos',
            process: 'global.process',
        },
    ])

    applyDotEnvPlugin(config)
    applyFileReplacements(config)

    addCopyRule('assets/**')
    addCopyRule('fonts/**')
    addCopyRule('**/*.+(jpg|png)')
    applyCopyRules(config)

    config
        .plugin('WatchStatePlugin')
        .use(WatchStatePlugin, [{ stats: env.stats !== false, verbose: !!env.verbose }])

    config.when(!!env.hmr, (chain) => {
        chain.plugin('HotModuleReplacementPlugin').use(rspack.HotModuleReplacementPlugin)
    })

    config.when(!!env.report, () => {
        warnOnce(
            'report',
            `--env.report is not supported: rspack has no bundle analyzer built in.
			 Add @rspack/plugin-... or rsdoctor from your rspack.config.ts instead.`,
        )
    })

    return config
}

/** The inspector modules power Chrome DevTools; Android only got them in 8.7. */
function shouldIncludeInspectorModules(platform: string): boolean {
    if (isVersionGte(getDependencyVersion('@nativescript/core'), '8.7.0')) {
        return platform === 'ios' || platform === 'android'
    }

    return platform === 'ios'
}
