// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "wamr-swift",
    platforms: [
        .iOS(.v13),
        .macOS(.v12),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "WamrFFI", targets: ["WamrFFI"])
    ],
    targets: [
        // C bridging module that provides the low-level FFI declarations
        // generated by UniFFI. This target links against the pre-built
        // Rust static library (libwamr_ffi.a).
        .target(
            name: "wamr_ffiFFI",
            path: "Sources/CWamrFFI",
            sources: ["dummy.c"],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("."),
            ],
            linkerSettings: [
                // Link against the Rust static library produced by cargo build
                .linkedLibrary("wamr_ffi"),
                // Tell the linker where to find libwamr_ffi.a
                .unsafeFlags(["-L", "Sources/CWamrFFI"]),
            ]
        ),
        // Swift wrapper generated by UniFFI from the UDL.
        .target(
            name: "WamrFFI",
            dependencies: ["wamr_ffiFFI"],
            path: "Sources/WamrFFI"
        ),
        .testTarget(
            name: "WamrFFITests",
            dependencies: ["WamrFFI"],
            path: "Tests/WamrFFITests"
        ),
    ],
    cLanguageStandard: .gnu11
)
