/* Minimal config.h for WAMR — generated for cc-rs build (non-CMake).
 *
 * In a full CMake build this would be generated by `configure_file()`.
 * We provide the subset of defines needed for a POSIX interpreter build.
 */

#ifndef WAMR_CONFIG_H
#define WAMR_CONFIG_H

/* ── Runtime features ───────────────────────────────────────────────── */

#define WASM_ENABLE_INTERP 1
#define WASM_ENABLE_FAST_INTERP 0
#define WASM_ENABLE_AOT 0
#define WASM_ENABLE_JIT 0
#define WASM_ENABLE_LAZY_JIT 0
#define WASM_ENABLE_LIBC_WASI 0
#define WASM_ENABLE_UVWASI 0
#define WASM_ENABLE_LIBC_BUILTIN 0
#define WASM_ENABLE_LIBC_EMCC 0
#define WASM_ENABLE_LIB_PTHREAD 0
#define WASM_ENABLE_LIB_WASI_THREADS 0
#define WASM_ENABLE_BH_MUTEX 0
#define WASM_ENABLE_SHARED_MEMORY 0
#define WASM_ENABLE_MEMORY_PROFILING 0
#define WASM_ENABLE_MEMORY_TRACING 0
#define WASM_ENABLE_PERF_PROFILING 0
#define WASM_ENABLE_DEBUG_INTERP 0
#define WASM_ENABLE_DEBUG_AOT 0
#define WASM_ENABLE_GC 0
#define WASM_ENABLE_TAIL_CALL 0
#define WASM_ENABLE_REF_TYPES 1
#define WASM_ENABLE_SIMD 0
#define WASM_ENABLE_BULK_MEMORY 1
#define WASM_ENABLE_THREAD_MGR 0
#define WASM_ENABLE_STATIC_PGO 0
#define WASM_ENABLE_WASI_NN 0
#define WASM_ENABLE_WASI_EPHEMERAL_NET 0
#define WASM_ENABLE_MULTI_MODULE 0
#define WASM_ENABLE_LIBC_WASI 0
#define WASM_ENABLE_SPEC_TEST 0
#define WASM_ENABLE_CUSTOM_NAME_SECTION 0

/* ── Platform ────────────────────────────────────────────────────────── */

#define BH_PLATFORM_DARWIN 1
#define BH_HAS_DLFCN 1
#define BH_HAS_STD_ATOMIC 1

/* ── Build target ────────────────────────────────────────────────────── */

/* WAMR's CMake normally sets one of the BUILD_TARGET_* macros. There is no
 * CMake here, and SwiftPM cannot vary a -D by architecture, so the target is
 * derived from the compiler's own arch macros instead. Without one of these,
 * wasm_runtime_invoke_native is compiled out of wasm_runtime_common.c and the
 * link fails with an undefined symbol. A build system that sets the macro
 * explicitly (cc-rs does) wins. */
#if !defined(BUILD_TARGET_X86_64) && !defined(BUILD_TARGET_AMD_64)     \
    && !defined(BUILD_TARGET_AARCH64) && !defined(BUILD_TARGET_X86_32) \
    && !defined(BUILD_TARGET_ARM) && !defined(BUILD_TARGET_THUMB)
#if defined(__aarch64__) || defined(__arm64__)
#define BUILD_TARGET_AARCH64 1
#elif defined(__x86_64__) || defined(_M_X64)
#define BUILD_TARGET_X86_64 1
#define BUILD_TARGET_AMD_64 1
#else
#error "NSCWamr: unsupported architecture — define BUILD_TARGET_* explicitly"
#endif
#endif

/* ── Memory ──────────────────────────────────────────────────────────── */

#define WASM_MEM_ALLOC_ALIGNMENT 8
#define APP_THREAD_STACK_SIZE_DEFAULT (64 * 1024)
#define APP_THREAD_STACK_SIZE_MAX (8 * 1024 * 1024)
#define DEFAULT_WASM_STACK_SIZE (64 * 1024)
#define WASM_PAGE_SIZE 65536
#define APP_HEAP_SIZE_MIN (4 * 1024)
#define APP_HEAP_SIZE_DEFAULT (16 * 1024 * 1024)

/* ── Miscellaneous ───────────────────────────────────────────────────── */

#define BH_MALLOC wasm_runtime_malloc
#define BH_FREE wasm_runtime_free

#define BH_DEBUG 0

/* Data structure defaults */
#define DEFAULT_QUEUE_LENGTH 64
#define DEFAULT_VECTOR_INIT_SIZE 8
#define BH_HASHMAP_INITIAL_SIZE 32

/* Interpreter configuration */
#define BLOCK_ADDR_CACHE_SIZE 64
#define BLOCK_ADDR_CONFLICT_SIZE 4
#define WASM_STACK_GUARD_SIZE (4 * 1024)

#define AOT_CURRENT_VERSION 4
#define APP_HEAP_SIZE_MAX (256 * 1024 * 1024)
#define WASM_CONST_EXPR_STACK_SIZE (4 * 1024)
#define WASM_TABLE_MAX_SIZE (1024 * 1024)
#define STACK_OVERFLOW_CHECK_GUARD_PAGE_COUNT 1

#endif /* WAMR_CONFIG_H */
