//! Raw Rust FFI bindings to the WAMR (WebAssembly Micro Runtime) C API.
//!
//! Generated by `bindgen` from `wasm_export.h` and `wasm_c_api.h` at build time.
//! The committed `bindings.rs` serves as a fallback reference.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
