// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
/**
 * WAMR (WebAssembly Micro Runtime) FFI bindings for Swift via UniFFI.
 */
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(wamr_ffiFFI)
import wamr_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_wamr_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_wamr_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWamrFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol WamrFunctionProtocol: AnyObject, Sendable {
    
    func callRaw(args: [UInt32]) throws  -> [UInt32]
    
    func signature()  -> FunctionSignature
    
}
open class WamrFunction: WamrFunctionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wamr_ffi_fn_clone_wamrfunction(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wamr_ffi_fn_free_wamrfunction(handle, $0) }
    }

    

    
open func callRaw(args: [UInt32])throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrfunction_call_raw(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(args),uniffiCallStatus
    )
})
}
    
open func signature() -> FunctionSignature  {
    return try!  FfiConverterTypeFunctionSignature_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrfunction_signature(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWamrFunction: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WamrFunction

    public static func lift(_ handle: UInt64) throws -> WamrFunction {
        return WamrFunction(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WamrFunction) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WamrFunction {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WamrFunction, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrFunction_lift(_ handle: UInt64) throws -> WamrFunction {
    return try FfiConverterTypeWamrFunction.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrFunction_lower(_ value: WamrFunction) -> UInt64 {
    return FfiConverterTypeWamrFunction.lower(value)
}






public protocol WamrModuleProtocol: AnyObject, Sendable {
    
    func instantiate() throws  -> WamrModuleInstance
    
    func moduleName()  -> String?
    
}
open class WamrModule: WamrModuleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wamr_ffi_fn_clone_wamrmodule(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wamr_ffi_fn_free_wamrmodule(handle, $0) }
    }

    

    
open func instantiate()throws  -> WamrModuleInstance  {
    return try  FfiConverterTypeWamrModuleInstance_lift(try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmodule_instantiate(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func moduleName() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmodule_module_name(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWamrModule: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WamrModule

    public static func lift(_ handle: UInt64) throws -> WamrModule {
        return WamrModule(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WamrModule) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WamrModule {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WamrModule, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrModule_lift(_ handle: UInt64) throws -> WamrModule {
    return try FfiConverterTypeWamrModule.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrModule_lower(_ value: WamrModule) -> UInt64 {
    return FfiConverterTypeWamrModule.lower(value)
}






public protocol WamrModuleInstanceProtocol: AnyObject, Sendable {
    
    func findFunction(name: String) throws  -> WamrFunction
    
    func getGlobal(name: String) throws  -> WasmValue
    
    func memorySize()  -> UInt32
    
    func moduleName()  -> String?
    
    func readMemory(offset: UInt32, length: UInt32) throws  -> [UInt8]
    
    func setGlobal(name: String, value: WasmValue) throws 
    
    func writeMemory(offset: UInt32, data: [UInt8]) throws 
    
}
open class WamrModuleInstance: WamrModuleInstanceProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wamr_ffi_fn_clone_wamrmoduleinstance(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wamr_ffi_fn_free_wamrmoduleinstance(handle, $0) }
    }

    

    
open func findFunction(name: String)throws  -> WamrFunction  {
    return try  FfiConverterTypeWamrFunction_lift(try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_find_function(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),uniffiCallStatus
    )
})
}
    
open func getGlobal(name: String)throws  -> WasmValue  {
    return try  FfiConverterTypeWasmValue_lift(try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_get_global(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),uniffiCallStatus
    )
})
}
    
open func memorySize() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_memory_size(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func moduleName() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_module_name(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func readMemory(offset: UInt32, length: UInt32)throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_read_memory(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(offset),
        FfiConverterUInt32.lower(length),uniffiCallStatus
    )
})
}
    
open func setGlobal(name: String, value: WasmValue)throws   {try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_set_global(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeWasmValue_lower(value),uniffiCallStatus
    )
}
}
    
open func writeMemory(offset: UInt32, data: [UInt8])throws   {try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrmoduleinstance_write_memory(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(offset),
        FfiConverterSequenceUInt8.lower(data),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWamrModuleInstance: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WamrModuleInstance

    public static func lift(_ handle: UInt64) throws -> WamrModuleInstance {
        return WamrModuleInstance(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WamrModuleInstance) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WamrModuleInstance {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WamrModuleInstance, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrModuleInstance_lift(_ handle: UInt64) throws -> WamrModuleInstance {
    return try FfiConverterTypeWamrModuleInstance.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrModuleInstance_lower(_ value: WamrModuleInstance) -> UInt64 {
    return FfiConverterTypeWamrModuleInstance.lower(value)
}






public protocol WamrRuntimeProtocol: AnyObject, Sendable {
    
    func loadModule(wasmBytes: [UInt8]) throws  -> WamrModule
    
    func version()  -> String
    
}
open class WamrRuntime: WamrRuntimeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wamr_ffi_fn_clone_wamrruntime(self.handle, $0) }
    }
public convenience init(config: RuntimeConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_constructor_wamrruntime_new(
        FfiConverterTypeRuntimeConfig_lower(config),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wamr_ffi_fn_free_wamrruntime(handle, $0) }
    }

    

    
open func loadModule(wasmBytes: [UInt8])throws  -> WamrModule  {
    return try  FfiConverterTypeWamrModule_lift(try rustCallWithError(FfiConverterTypeWamrError_lift) {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrruntime_load_module(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt8.lower(wasmBytes),uniffiCallStatus
    )
})
}
    
open func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_wamr_ffi_fn_method_wamrruntime_version(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWamrRuntime: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WamrRuntime

    public static func lift(_ handle: UInt64) throws -> WamrRuntime {
        return WamrRuntime(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WamrRuntime) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WamrRuntime {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WamrRuntime, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrRuntime_lift(_ handle: UInt64) throws -> WamrRuntime {
    return try FfiConverterTypeWamrRuntime.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrRuntime_lower(_ value: WamrRuntime) -> UInt64 {
    return FfiConverterTypeWamrRuntime.lower(value)
}




public struct FunctionSignature: Equatable, Hashable {
    public var raw: String
    public var params: [WasmValueType]
    public var results: [WasmValueType]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(raw: String, params: [WasmValueType], results: [WasmValueType]) {
        self.raw = raw
        self.params = params
        self.results = results
    }

    

    
}

#if compiler(>=6)
extension FunctionSignature: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFunctionSignature: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FunctionSignature {
        return
            try FunctionSignature(
                raw: FfiConverterString.read(from: &buf), 
                params: FfiConverterSequenceTypeWasmValueType.read(from: &buf), 
                results: FfiConverterSequenceTypeWasmValueType.read(from: &buf)
        )
    }

    public static func write(_ value: FunctionSignature, into buf: inout [UInt8]) {
        FfiConverterString.write(value.raw, into: &buf)
        FfiConverterSequenceTypeWasmValueType.write(value.params, into: &buf)
        FfiConverterSequenceTypeWasmValueType.write(value.results, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFunctionSignature_lift(_ buf: RustBuffer) throws -> FunctionSignature {
    return try FfiConverterTypeFunctionSignature.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFunctionSignature_lower(_ value: FunctionSignature) -> RustBuffer {
    return FfiConverterTypeFunctionSignature.lower(value)
}


public struct RuntimeConfig: Equatable, Hashable {
    public var executionTier: ExecutionTier
    public var defaultStackSize: UInt32
    public var maxMemoryPages: UInt32
    public var wasiEnabled: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(executionTier: ExecutionTier, defaultStackSize: UInt32, maxMemoryPages: UInt32, wasiEnabled: Bool) {
        self.executionTier = executionTier
        self.defaultStackSize = defaultStackSize
        self.maxMemoryPages = maxMemoryPages
        self.wasiEnabled = wasiEnabled
    }

    

    
}

#if compiler(>=6)
extension RuntimeConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRuntimeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RuntimeConfig {
        return
            try RuntimeConfig(
                executionTier: FfiConverterTypeExecutionTier.read(from: &buf), 
                defaultStackSize: FfiConverterUInt32.read(from: &buf), 
                maxMemoryPages: FfiConverterUInt32.read(from: &buf), 
                wasiEnabled: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: RuntimeConfig, into buf: inout [UInt8]) {
        FfiConverterTypeExecutionTier.write(value.executionTier, into: &buf)
        FfiConverterUInt32.write(value.defaultStackSize, into: &buf)
        FfiConverterUInt32.write(value.maxMemoryPages, into: &buf)
        FfiConverterBool.write(value.wasiEnabled, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeConfig_lift(_ buf: RustBuffer) throws -> RuntimeConfig {
    return try FfiConverterTypeRuntimeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeConfig_lower(_ value: RuntimeConfig) -> RustBuffer {
    return FfiConverterTypeRuntimeConfig.lower(value)
}


public struct WasmValue: Equatable, Hashable {
    public var kind: WasmValueType
    public var bitsLo: UInt32
    public var bitsHi: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: WasmValueType, bitsLo: UInt32, bitsHi: UInt32) {
        self.kind = kind
        self.bitsLo = bitsLo
        self.bitsHi = bitsHi
    }

    

    
}

#if compiler(>=6)
extension WasmValue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWasmValue: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WasmValue {
        return
            try WasmValue(
                kind: FfiConverterTypeWasmValueType.read(from: &buf), 
                bitsLo: FfiConverterUInt32.read(from: &buf), 
                bitsHi: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: WasmValue, into buf: inout [UInt8]) {
        FfiConverterTypeWasmValueType.write(value.kind, into: &buf)
        FfiConverterUInt32.write(value.bitsLo, into: &buf)
        FfiConverterUInt32.write(value.bitsHi, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWasmValue_lift(_ buf: RustBuffer) throws -> WasmValue {
    return try FfiConverterTypeWasmValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWasmValue_lower(_ value: WasmValue) -> RustBuffer {
    return FfiConverterTypeWasmValue.lower(value)
}



public enum ExecutionTier: Equatable, Hashable {
    
    case interpreter
    case fastJit
    case llvmjit
    case aot





}

#if compiler(>=6)
extension ExecutionTier: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExecutionTier: FfiConverterRustBuffer {
    typealias SwiftType = ExecutionTier

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExecutionTier {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .interpreter
        
        case 2: return .fastJit
        
        case 3: return .llvmjit
        
        case 4: return .aot
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ExecutionTier, into buf: inout [UInt8]) {
        switch value {
        
        
        case .interpreter:
            writeInt(&buf, Int32(1))
        
        
        case .fastJit:
            writeInt(&buf, Int32(2))
        
        
        case .llvmjit:
            writeInt(&buf, Int32(3))
        
        
        case .aot:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExecutionTier_lift(_ buf: RustBuffer) throws -> ExecutionTier {
    return try FfiConverterTypeExecutionTier.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExecutionTier_lower(_ value: ExecutionTier) -> RustBuffer {
    return FfiConverterTypeExecutionTier.lower(value)
}



public 
enum WamrError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InitFailed(message: String
    )
    case ModuleLoadFailed(message: String
    )
    case InstantiationFailed(message: String
    )
    case FunctionNotFound(message: String
    )
    case CallFailed(message: String
    )
    case MemoryAccessFailed(message: String
    )
    case GlobalAccessFailed(message: String
    )
    case InvalidArgument(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension WamrError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWamrError: FfiConverterRustBuffer {
    typealias SwiftType = WamrError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WamrError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ModuleLoadFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InstantiationFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .FunctionNotFound(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .CallFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .MemoryAccessFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 7: return .GlobalAccessFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .InvalidArgument(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WamrError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InitFailed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ModuleLoadFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InstantiationFailed(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .FunctionNotFound(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .CallFailed(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .MemoryAccessFailed(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .GlobalAccessFailed(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidArgument(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrError_lift(_ buf: RustBuffer) throws -> WamrError {
    return try FfiConverterTypeWamrError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWamrError_lower(_ value: WamrError) -> RustBuffer {
    return FfiConverterTypeWamrError.lower(value)
}



public enum WasmValueType: Equatable, Hashable {
    
    case i32
    case i64
    case f32
    case f64





}

#if compiler(>=6)
extension WasmValueType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWasmValueType: FfiConverterRustBuffer {
    typealias SwiftType = WasmValueType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WasmValueType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .i32
        
        case 2: return .i64
        
        case 3: return .f32
        
        case 4: return .f64
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WasmValueType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .i32:
            writeInt(&buf, Int32(1))
        
        
        case .i64:
            writeInt(&buf, Int32(2))
        
        
        case .f32:
            writeInt(&buf, Int32(3))
        
        
        case .f64:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWasmValueType_lift(_ buf: RustBuffer) throws -> WasmValueType {
    return try FfiConverterTypeWasmValueType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWasmValueType_lower(_ value: WasmValueType) -> RustBuffer {
    return FfiConverterTypeWasmValueType.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWasmValueType: FfiConverterRustBuffer {
    typealias SwiftType = [WasmValueType]

    public static func write(_ value: [WasmValueType], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWasmValueType.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WasmValueType] {
        let len: Int32 = try readInt(&buf)
        var seq = [WasmValueType]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWasmValueType.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_wamr_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrfunction_call_raw() != 51340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrfunction_signature() != 50326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmodule_instantiate() != 26346) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmodule_module_name() != 1668) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_find_function() != 32440) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_get_global() != 28004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_memory_size() != 13947) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_module_name() != 56850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_read_memory() != 40022) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_set_global() != 58711) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrmoduleinstance_write_memory() != 41747) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrruntime_load_module() != 50554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_method_wamrruntime_version() != 37732) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wamr_ffi_checksum_constructor_wamrruntime_new() != 38152) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWamrFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all