/* Minimal config.h for WAMR — generated for cc-rs build (non-CMake).
 *
 * In a full CMake build this would be generated by `configure_file()`.
 * We provide the subset of defines needed for a POSIX interpreter build.
 */

#ifndef WAMR_CONFIG_H
#define WAMR_CONFIG_H

/* ── Runtime features ───────────────────────────────────────────────── */

#define WASM_ENABLE_INTERP 1
#define WASM_ENABLE_FAST_INTERP 0
#define WASM_ENABLE_AOT 0
#define WASM_ENABLE_JIT 0
#define WASM_ENABLE_LAZY_JIT 0
#define WASM_ENABLE_LIBC_WASI 0
#define WASM_ENABLE_UVWASI 0
#define WASM_ENABLE_LIBC_BUILTIN 0
#define WASM_ENABLE_LIBC_EMCC 0
#define WASM_ENABLE_LIB_PTHREAD 0
#define WASM_ENABLE_LIB_WASI_THREADS 0
#define WASM_ENABLE_BH_MUTEX 0
#define WASM_ENABLE_SHARED_MEMORY 0
#define WASM_ENABLE_MEMORY_PROFILING 0
#define WASM_ENABLE_MEMORY_TRACING 0
#define WASM_ENABLE_PERF_PROFILING 0
#define WASM_ENABLE_DEBUG_INTERP 0
#define WASM_ENABLE_DEBUG_AOT 0
#define WASM_ENABLE_GC 0
#define WASM_ENABLE_TAIL_CALL 0
#define WASM_ENABLE_REF_TYPES 0
#define WASM_ENABLE_SIMD 0
#define WASM_ENABLE_BULK_MEMORY 0
#define WASM_ENABLE_THREAD_MGR 0
#define WASM_ENABLE_STATIC_PGO 0
#define WASM_ENABLE_WASI_NN 0
#define WASM_ENABLE_WASI_EPHEMERAL_NET 0
#define WASM_ENABLE_MULTI_MODULE 0
#define WASM_ENABLE_LIBC_WASI 0
#define WASM_ENABLE_SPEC_TEST 0
#define WASM_ENABLE_CUSTOM_NAME_SECTION 0

/* ── Platform ────────────────────────────────────────────────────────── */

#define BH_PLATFORM_DARWIN 1
#define BH_HAS_DLFCN 1
#define BH_HAS_STD_ATOMIC 1

/* ── Memory ──────────────────────────────────────────────────────────── */

#define WASM_MEM_ALLOC_ALIGNMENT 8
#define APP_THREAD_STACK_SIZE_DEFAULT (64 * 1024)
#define APP_THREAD_STACK_SIZE_MAX (8 * 1024 * 1024)
#define DEFAULT_WASM_STACK_SIZE (64 * 1024)
#define WASM_PAGE_SIZE 65536
#define APP_HEAP_SIZE_MIN (4 * 1024)
#define APP_HEAP_SIZE_DEFAULT (16 * 1024 * 1024)

/* ── Miscellaneous ───────────────────────────────────────────────────── */

#define BH_MALLOC wasm_runtime_malloc
#define BH_FREE wasm_runtime_free

#define BH_DEBUG 0

/* Data structure defaults */
#define DEFAULT_QUEUE_LENGTH 64
#define DEFAULT_VECTOR_INIT_SIZE 8
#define BH_HASHMAP_INITIAL_SIZE 32

/* Interpreter configuration */
#define BLOCK_ADDR_CACHE_SIZE 64
#define BLOCK_ADDR_CONFLICT_SIZE 4
#define WASM_STACK_GUARD_SIZE (4 * 1024)

#endif /* WAMR_CONFIG_H */
#define AOT_CURRENT_VERSION 4
#define APP_HEAP_SIZE_MAX (256 * 1024 * 1024)
#define WASM_CONST_EXPR_STACK_SIZE (4 * 1024)
#define WASM_TABLE_MAX_SIZE (1024 * 1024)
#define STACK_OVERFLOW_CHECK_GUARD_PAGE_COUNT 1
