// Syncs the canonical WAMR sources (src/vendors/wamr) into the iOS Swift
// package, and the generated test fixtures into the platform test suites.
//
// SwiftPM requires a target's sources to live inside the package directory,
// so the iOS package carries a script-managed copy. The Android build
// compiles the canonical sources directly and needs no copy.
//
// Usage: node tools/sync-wamr.mjs
import { cpSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const vendorDir = join(pkgRoot, 'src', 'vendors', 'wamr');
const cTargetDir = join(pkgRoot, 'platforms', 'ios', 'NSCWamr', 'Sources', 'CWamr');
const fixturesDir = join(pkgRoot, 'test-support', 'fixtures');

// Public headers exposed to Swift via the SwiftPM include dir.
// These are the top-level WAMR API headers that the Swift layer needs.
const publicHeaders = [
  'wasm_export.h',
  'wasm_c_api.h',
  'bh_platform.h',
  'bh_read_file.h',
];

// Files and directories to exclude (build artifacts, platform-specific backends
// not needed on mobile, and unrelated tools).
const excludedDirs = new Set([
  '.git',
  '.DS_Store',
  'build-scripts',
  'compilation',
  'doc',
  'language-bindings',
  'samples',
  'test-tools',
  'tests',
  'wamr-compiler',
  'wamrc',
  'product-mini',
]);

const excludedFiles = new Set([
  '.DS_Store',
  '.gitignore',
  '.gitmodules',
  'CMakeLists.txt',
  'Makefile',
  'README.md',
  'LICENSE',
]);

function copyDirRecursive(srcDir, destDir) {
  mkdirSync(destDir, { recursive: true });
  let count = 0;
  for (const entry of readdirSync(srcDir)) {
    const srcPath = join(srcDir, entry);
    const destPath = join(destDir, entry);
    const stat = statSync(srcPath);

    if (stat.isDirectory()) {
      if (excludedDirs.has(entry)) continue;
      count += copyDirRecursive(srcPath, destPath);
    } else {
      if (excludedFiles.has(entry)) continue;
      cpSync(srcPath, destPath);
      count++;
    }
  }
  return count;
}

rmSync(cTargetDir, { recursive: true, force: true });
mkdirSync(join(cTargetDir, 'include'), { recursive: true });

const copied = copyDirRecursive(vendorDir, cTargetDir);

// Symlink or copy public headers into the include directory so SwiftPM's
// publicHeadersPath can find them. We look for the header files anywhere
// in the copied tree and create a relative symlink (or copy) in include/.
function findAndLinkHeaders(baseDir, headers, includeDir) {
  const found = new Map();
  function walk(dir) {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else if (headers.includes(entry) && !found.has(entry)) {
        found.set(entry, relative(includeDir, full));
      }
    }
  }
  walk(baseDir);
  for (const [name, relPath] of found) {
    writeFileSync(join(includeDir, name), `/* Redirect to ${relPath} — see sync-wamr.mjs */\n#include "${relPath}"\n`);
  }
  return found.size;
}

const headerCount = findAndLinkHeaders(cTargetDir, publicHeaders, join(cTargetDir, 'include'));

writeFileSync(
  join(cTargetDir, 'README.md'),
  '<!-- GENERATED by tools/sync-wamr.mjs — do not edit. Canonical sources: src/vendors/wamr -->\n',
);
console.log(`synced ${copied} WAMR files (${headerCount} public headers) -> ${cTargetDir}`);

// Fixtures for the Swift test target and the Android host tests.
const targets = [
  join(pkgRoot, 'platforms', 'ios', 'NSCWamr', 'Tests', 'NSCWamrTests', 'Fixtures'),
  join(pkgRoot, 'platforms', 'android', 'wamr-android', 'hosttest', 'src', 'test', 'resources', 'fixtures'),
];
for (const dir of targets) {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  for (const f of readdirSync(fixturesDir)) cpSync(join(fixturesDir, f), join(dir, f));
  console.log(`synced fixtures -> ${dir}`);
}
