//! Raw Rust FFI bindings to the wasm3 C API.
//!
//! Generated by `bindgen` from `wasm3.h` at build time.
//! The `nsc_global_get` / `nsc_global_set` shim functions (previously in
//! `nsc_wasm3_shim.c`) are now pure Rust — see below.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ── NSC wasm3 shim: global access helpers (pure Rust) ─────────────────────
//
// wasm3 uses a tagged-value union (`M3TaggedValue`) for globals that is
// awkward for automatic binding generators.  These two Rust functions replace
// the old `nsc_wasm3_shim.c`.

use std::ffi::c_char;

/// Reads a wasm3 global into a type code and raw 64-bit bits.
/// Returns null on success, or an error string pointer.
///
/// # Safety
/// `global` must be a valid IM3Global pointer.
pub unsafe fn nsc_global_get(
    global: IM3Global,
    o_type: *mut i32,
    o_bits: *mut u64,
) -> *const c_char {
    let mut tagged: M3TaggedValue = std::mem::zeroed();
    let result = m3_GetGlobal(global, &mut tagged);
    if !result.is_null() {
        return result;
    }

    unsafe {
        *o_type = tagged.type_ as i32;
        *o_bits = 0;
        match tagged.type_ as u32 {
            x if x == c_m3Type_i32 as u32 => *o_bits = tagged.value.i32 as u64,
            x if x == c_m3Type_i64 as u32 => *o_bits = tagged.value.i64,
            x if x == c_m3Type_f32 as u32 => {
                let bits = tagged.value.f32.to_bits();
                *o_bits = bits as u64;
            }
            x if x == c_m3Type_f64 as u32 => {
                *o_bits = tagged.value.f64.to_bits();
            }
            _ => return m3Err_globalTypeMismatch,
        }
    }
    std::ptr::null()
}

/// Writes a wasm3 global from a type code and raw 64-bit bits.
/// Returns null on success, or an error string pointer.
///
/// # Safety
/// `global` must be a valid IM3Global pointer.
pub unsafe fn nsc_global_set(
    global: IM3Global,
    i_type: i32,
    i_bits: u64,
) -> *const c_char {
    let mut tagged: M3TaggedValue = unsafe { std::mem::zeroed() };
    tagged.type_ = unsafe { std::mem::transmute::<i32, M3ValueType>(i_type) };

    unsafe {
        match i_type as u32 {
            x if x == c_m3Type_i32 as u32 => tagged.value.i32 = i_bits as u32,
            x if x == c_m3Type_i64 as u32 => tagged.value.i64 = i_bits,
            x if x == c_m3Type_f32 as u32 => {
                tagged.value.f32 = f32::from_bits(i_bits as u32);
            }
            x if x == c_m3Type_f64 as u32 => {
                tagged.value.f64 = f64::from_bits(i_bits);
            }
            _ => return m3Err_globalTypeMismatch,
        }
    }

    m3_SetGlobal(global, &tagged)
}
