//! Raw Rust FFI bindings to the wasm3 C API.
//!
//! Generated by `bindgen` from `wasm3.h` and `nsc_wasm3_shim.h` at build time.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
