/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone)]
pub struct NativeSymbol {
    pub symbol: *const ::std::os::raw::c_char,
    pub func_ptr: *mut ::std::os::raw::c_void,
    pub signature: *const ::std::os::raw::c_char,
    pub attachment: *mut ::std::os::raw::c_void,
}
impl Default for NativeSymbol {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn get_base_lib_export_apis(p_base_lib_apis: *mut *mut NativeSymbol) -> u32;
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct WASMModuleCommon {
    _unused: [u8; 0],
}
pub type wasm_module_t = *mut WASMModuleCommon;
pub const wasm_import_export_kind_t_WASM_IMPORT_EXPORT_KIND_FUNC: wasm_import_export_kind_t = 0;
pub const wasm_import_export_kind_t_WASM_IMPORT_EXPORT_KIND_TABLE: wasm_import_export_kind_t = 1;
pub const wasm_import_export_kind_t_WASM_IMPORT_EXPORT_KIND_MEMORY: wasm_import_export_kind_t = 2;
pub const wasm_import_export_kind_t_WASM_IMPORT_EXPORT_KIND_GLOBAL: wasm_import_export_kind_t = 3;
pub type wasm_import_export_kind_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WASMFuncType {
    _unused: [u8; 0],
}
pub type wasm_func_type_t = *mut WASMFuncType;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WASMTableType {
    _unused: [u8; 0],
}
pub type wasm_table_type_t = *mut WASMTableType;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WASMGlobalType {
    _unused: [u8; 0],
}
pub type wasm_global_type_t = *mut WASMGlobalType;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WASMMemory {
    _unused: [u8; 0],
}
pub type WASMMemoryType = WASMMemory;
pub type wasm_memory_type_t = *mut WASMMemoryType;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_import_t {
    pub module_name: *const ::std::os::raw::c_char,
    pub name: *const ::std::os::raw::c_char,
    pub kind: wasm_import_export_kind_t,
    pub linked: bool,
    pub u: wasm_import_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union wasm_import_t__bindgen_ty_1 {
    pub func_type: wasm_func_type_t,
    pub table_type: wasm_table_type_t,
    pub global_type: wasm_global_type_t,
    pub memory_type: wasm_memory_type_t,
}
impl Default for wasm_import_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for wasm_import_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_export_t {
    pub name: *const ::std::os::raw::c_char,
    pub kind: wasm_import_export_kind_t,
    pub u: wasm_export_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union wasm_export_t__bindgen_ty_1 {
    pub func_type: wasm_func_type_t,
    pub table_type: wasm_table_type_t,
    pub global_type: wasm_global_type_t,
    pub memory_type: wasm_memory_type_t,
}
impl Default for wasm_export_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for wasm_export_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct WASMModuleInstanceCommon {
    _unused: [u8; 0],
}
pub type wasm_module_inst_t = *mut WASMModuleInstanceCommon;
pub type WASMFunctionInstanceCommon = ::std::os::raw::c_void;
pub type wasm_function_inst_t = *mut WASMFunctionInstanceCommon;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WASMMemoryInstance {
    _unused: [u8; 0],
}
pub type wasm_memory_inst_t = *mut WASMMemoryInstance;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_frame_t {
    pub instance: *mut ::std::os::raw::c_void,
    pub module_offset: u32,
    pub func_index: u32,
    pub func_offset: u32,
    pub func_name_wp: *const ::std::os::raw::c_char,
    pub sp: *mut u32,
    pub frame_ref: *mut u8,
    pub lp: *mut u32,
}
impl Default for wasm_frame_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type WASMCApiFrame = wasm_frame_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_section_t {
    pub next: *mut wasm_section_t,
    pub section_type: ::std::os::raw::c_int,
    pub section_body: *mut u8,
    pub section_body_size: u32,
}
impl Default for wasm_section_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type wasm_section_list_t = *mut wasm_section_t;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct WASMExecEnv {
    _unused: [u8; 0],
}
pub type wasm_exec_env_t = *mut WASMExecEnv;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WASMSharedHeap {
    _unused: [u8; 0],
}
pub type wasm_shared_heap_t = *mut WASMSharedHeap;
pub const package_type_t_Wasm_Module_Bytecode: package_type_t = 0;
pub const package_type_t_Wasm_Module_AoT: package_type_t = 1;
pub const package_type_t_Package_Type_Unknown: package_type_t = 65535;
pub type package_type_t = ::std::os::raw::c_uint;
pub const mem_alloc_type_t_Alloc_With_Pool: mem_alloc_type_t = 0;
pub const mem_alloc_type_t_Alloc_With_Allocator: mem_alloc_type_t = 1;
pub const mem_alloc_type_t_Alloc_With_System_Allocator: mem_alloc_type_t = 2;
pub type mem_alloc_type_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union MemAllocOption {
    pub pool: MemAllocOption__bindgen_ty_1,
    pub allocator: MemAllocOption__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MemAllocOption__bindgen_ty_1 {
    pub heap_buf: *mut ::std::os::raw::c_void,
    pub heap_size: u32,
}
impl Default for MemAllocOption__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MemAllocOption__bindgen_ty_2 {
    pub malloc_func: *mut ::std::os::raw::c_void,
    pub realloc_func: *mut ::std::os::raw::c_void,
    pub free_func: *mut ::std::os::raw::c_void,
    pub user_data: *mut ::std::os::raw::c_void,
}
impl Default for MemAllocOption__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for MemAllocOption {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct mem_alloc_info_t {
    pub total_size: u32,
    pub total_free_size: u32,
    pub highmark_size: u32,
}
pub const RunningMode_Mode_Interp: RunningMode = 1;
pub const RunningMode_Mode_Fast_JIT: RunningMode = 2;
pub const RunningMode_Mode_LLVM_JIT: RunningMode = 3;
pub const RunningMode_Mode_Multi_Tier_JIT: RunningMode = 4;
pub type RunningMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RuntimeInitArgs {
    pub mem_alloc_type: mem_alloc_type_t,
    pub mem_alloc_option: MemAllocOption,
    pub native_module_name: *const ::std::os::raw::c_char,
    pub native_symbols: *mut NativeSymbol,
    pub n_native_symbols: u32,
    pub max_thread_num: u32,
    pub ip_addr: [::std::os::raw::c_char; 128usize],
    pub unused: ::std::os::raw::c_int,
    pub instance_port: ::std::os::raw::c_int,
    pub fast_jit_code_cache_size: u32,
    pub gc_heap_size: u32,
    pub running_mode: RunningMode,
    pub llvm_jit_opt_level: u32,
    pub llvm_jit_size_level: u32,
    pub segue_flags: u32,
    pub enable_linux_perf: bool,
}
impl Default for RuntimeInitArgs {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct LoadArgs {
    pub name: *mut ::std::os::raw::c_char,
    pub clone_wasm_binary: bool,
    pub wasm_binary_freeable: bool,
    pub no_resolve: bool,
}
impl Default for LoadArgs {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct InstantiationArgs {
    pub default_stack_size: u32,
    pub host_managed_heap_size: u32,
    pub max_memory_pages: u32,
}
pub type wasm_valkind_t = u8;
pub const wasm_valkind_enum_WASM_I32: wasm_valkind_enum = 0;
pub const wasm_valkind_enum_WASM_I64: wasm_valkind_enum = 1;
pub const wasm_valkind_enum_WASM_F32: wasm_valkind_enum = 2;
pub const wasm_valkind_enum_WASM_F64: wasm_valkind_enum = 3;
pub const wasm_valkind_enum_WASM_V128: wasm_valkind_enum = 4;
pub const wasm_valkind_enum_WASM_EXTERNREF: wasm_valkind_enum = 128;
pub const wasm_valkind_enum_WASM_FUNCREF: wasm_valkind_enum = 129;
pub type wasm_valkind_enum = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_ref_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_val_t {
    pub kind: wasm_valkind_t,
    pub _paddings: [u8; 7usize],
    pub of: wasm_val_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union wasm_val_t__bindgen_ty_1 {
    pub i32_: i32,
    pub i64_: i64,
    pub f32_: f32,
    pub f64_: f64,
    pub foreign: usize,
    pub ref_: *mut wasm_ref_t,
}
impl Default for wasm_val_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for wasm_val_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_global_inst_t {
    pub kind: wasm_valkind_t,
    pub is_mutable: bool,
    pub global_data: *mut ::std::os::raw::c_void,
}
impl Default for wasm_global_inst_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_table_inst_t {
    pub elem_kind: wasm_valkind_t,
    pub cur_size: u32,
    pub max_size: u32,
    pub elems: *mut ::std::os::raw::c_void,
}
impl Default for wasm_table_inst_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const log_level_t_WASM_LOG_LEVEL_FATAL: log_level_t = 0;
pub const log_level_t_WASM_LOG_LEVEL_ERROR: log_level_t = 1;
pub const log_level_t_WASM_LOG_LEVEL_WARNING: log_level_t = 2;
pub const log_level_t_WASM_LOG_LEVEL_DEBUG: log_level_t = 3;
pub const log_level_t_WASM_LOG_LEVEL_VERBOSE: log_level_t = 4;
pub type log_level_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct SharedHeapInitArgs {
    pub size: u32,
}
unsafe extern "C" {
    pub fn wasm_runtime_init() -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_full_init(init_args: *mut RuntimeInitArgs) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_log_level(level: log_level_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_is_running_mode_supported(running_mode: RunningMode) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_default_running_mode(running_mode: RunningMode) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_destroy();
}
unsafe extern "C" {
    pub fn wasm_runtime_malloc(size: ::std::os::raw::c_uint) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_realloc(
        ptr: *mut ::std::os::raw::c_void,
        size: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_free(ptr: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_runtime_get_mem_alloc_info(mem_alloc_info: *mut mem_alloc_info_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_file_package_type(buf: *const u8, size: u32) -> package_type_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_module_package_type(module: wasm_module_t) -> package_type_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_file_package_version(buf: *const u8, size: u32) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_module_package_version(module: wasm_module_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_current_package_version(package_type: package_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_is_xip_file(buf: *const u8, size: u32) -> bool;
}
pub type module_reader = ::std::option::Option<
    unsafe extern "C" fn(
        module_type: package_type_t,
        module_name: *const ::std::os::raw::c_char,
        p_buffer: *mut *mut u8,
        p_size: *mut u32,
    ) -> bool,
>;
pub type module_destroyer = ::std::option::Option<unsafe extern "C" fn(buffer: *mut u8, size: u32)>;
unsafe extern "C" {
    pub fn wasm_runtime_set_module_reader(reader: module_reader, destroyer: module_destroyer);
}
unsafe extern "C" {
    pub fn wasm_runtime_register_module(
        module_name: *const ::std::os::raw::c_char,
        module: wasm_module_t,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_find_module_registered(
        module_name: *const ::std::os::raw::c_char,
    ) -> wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_load(
        buf: *mut u8,
        size: u32,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_load_ex(
        buf: *mut u8,
        size: u32,
        args: *const LoadArgs,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_resolve_symbols(module: wasm_module_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_load_from_sections(
        section_list: wasm_section_list_t,
        is_aot: bool,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_unload(module: wasm_module_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_get_module_hash(module: wasm_module_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_wasi_args_ex(
        module: wasm_module_t,
        dir_list: *mut *const ::std::os::raw::c_char,
        dir_count: u32,
        map_dir_list: *mut *const ::std::os::raw::c_char,
        map_dir_count: u32,
        env: *mut *const ::std::os::raw::c_char,
        env_count: u32,
        argv: *mut *mut ::std::os::raw::c_char,
        argc: ::std::os::raw::c_int,
        stdinfd: i64,
        stdoutfd: i64,
        stderrfd: i64,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_set_wasi_args(
        module: wasm_module_t,
        dir_list: *mut *const ::std::os::raw::c_char,
        dir_count: u32,
        map_dir_list: *mut *const ::std::os::raw::c_char,
        map_dir_count: u32,
        env: *mut *const ::std::os::raw::c_char,
        env_count: u32,
        argv: *mut *mut ::std::os::raw::c_char,
        argc: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_set_wasi_addr_pool(
        module: wasm_module_t,
        addr_pool: *mut *const ::std::os::raw::c_char,
        addr_pool_size: u32,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_set_wasi_ns_lookup_pool(
        module: wasm_module_t,
        ns_lookup_pool: *mut *const ::std::os::raw::c_char,
        ns_lookup_pool_size: u32,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_instantiate(
        module: wasm_module_t,
        default_stack_size: u32,
        host_managed_heap_size: u32,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> wasm_module_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_instantiate_ex(
        module: wasm_module_t,
        args: *const InstantiationArgs,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> wasm_module_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_running_mode(
        module_inst: wasm_module_inst_t,
        running_mode: RunningMode,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_running_mode(module_inst: wasm_module_inst_t) -> RunningMode;
}
unsafe extern "C" {
    pub fn wasm_runtime_deinstantiate(module_inst: wasm_module_inst_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_get_module(module_inst: wasm_module_inst_t) -> wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_is_wasi_mode(module_inst: wasm_module_inst_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_lookup_wasi_start_function(
        module_inst: wasm_module_inst_t,
    ) -> wasm_function_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_wasi_exit_code(module_inst: wasm_module_inst_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_lookup_function(
        module_inst: wasm_module_inst_t,
        name: *const ::std::os::raw::c_char,
    ) -> wasm_function_inst_t;
}
unsafe extern "C" {
    pub fn wasm_func_get_param_count(
        func_inst: wasm_function_inst_t,
        module_inst: wasm_module_inst_t,
    ) -> u32;
}
unsafe extern "C" {
    pub fn wasm_func_get_result_count(
        func_inst: wasm_function_inst_t,
        module_inst: wasm_module_inst_t,
    ) -> u32;
}
unsafe extern "C" {
    pub fn wasm_func_get_param_types(
        func_inst: wasm_function_inst_t,
        module_inst: wasm_module_inst_t,
        param_types: *mut wasm_valkind_t,
    );
}
unsafe extern "C" {
    pub fn wasm_func_get_result_types(
        func_inst: wasm_function_inst_t,
        module_inst: wasm_module_inst_t,
        result_types: *mut wasm_valkind_t,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_create_exec_env(
        module_inst: wasm_module_inst_t,
        stack_size: u32,
    ) -> wasm_exec_env_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_destroy_exec_env(exec_env: wasm_exec_env_t);
}
unsafe extern "C" {
    pub fn wasm_copy_callstack(
        exec_env: wasm_exec_env_t,
        buffer: *mut wasm_frame_t,
        length: u32,
        skip_n: u32,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_exec_env_singleton(module_inst: wasm_module_inst_t) -> wasm_exec_env_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_start_debug_instance_with_port(exec_env: wasm_exec_env_t, port: i32)
    -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_start_debug_instance(exec_env: wasm_exec_env_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_init_thread_env() -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_destroy_thread_env();
}
unsafe extern "C" {
    pub fn wasm_runtime_thread_env_inited() -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_module_inst(exec_env: wasm_exec_env_t) -> wasm_module_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_module_inst(exec_env: wasm_exec_env_t, module_inst: wasm_module_inst_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_lookup_memory(
        module_inst: wasm_module_inst_t,
        name: *const ::std::os::raw::c_char,
    ) -> wasm_memory_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_default_memory(module_inst: wasm_module_inst_t) -> wasm_memory_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_memory(
        module_inst: wasm_module_inst_t,
        index: u32,
    ) -> wasm_memory_inst_t;
}
unsafe extern "C" {
    pub fn wasm_memory_get_cur_page_count(memory_inst: wasm_memory_inst_t) -> u64;
}
unsafe extern "C" {
    pub fn wasm_memory_get_max_page_count(memory_inst: wasm_memory_inst_t) -> u64;
}
unsafe extern "C" {
    pub fn wasm_memory_get_bytes_per_page(memory_inst: wasm_memory_inst_t) -> u64;
}
unsafe extern "C" {
    pub fn wasm_memory_get_shared(memory_inst: wasm_memory_inst_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_memory_get_base_address(
        memory_inst: wasm_memory_inst_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_memory_enlarge(memory_inst: wasm_memory_inst_t, inc_page_count: u64) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_call_wasm(
        exec_env: wasm_exec_env_t,
        function: wasm_function_inst_t,
        argc: u32,
        argv: *mut u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_call_wasm_a(
        exec_env: wasm_exec_env_t,
        function: wasm_function_inst_t,
        num_results: u32,
        results: *mut wasm_val_t,
        num_args: u32,
        args: *mut wasm_val_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_call_wasm_v(
        exec_env: wasm_exec_env_t,
        function: wasm_function_inst_t,
        num_results: u32,
        results: *mut wasm_val_t,
        num_args: u32,
        ...
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_call_indirect(
        exec_env: wasm_exec_env_t,
        element_index: u32,
        argc: u32,
        argv: *mut u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_application_execute_main(
        module_inst: wasm_module_inst_t,
        argc: i32,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_application_execute_func(
        module_inst: wasm_module_inst_t,
        name: *const ::std::os::raw::c_char,
        argc: i32,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_exception(
        module_inst: wasm_module_inst_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_exception(
        module_inst: wasm_module_inst_t,
        exception: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_clear_exception(module_inst: wasm_module_inst_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_terminate(module_inst: wasm_module_inst_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_set_custom_data(
        module_inst: wasm_module_inst_t,
        custom_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_get_custom_data(
        module_inst: wasm_module_inst_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_bounds_checks(module_inst: wasm_module_inst_t, enable: bool);
}
unsafe extern "C" {
    pub fn wasm_runtime_is_bounds_checks_enabled(module_inst: wasm_module_inst_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_module_malloc(
        module_inst: wasm_module_inst_t,
        size: u64,
        p_native_addr: *mut *mut ::std::os::raw::c_void,
    ) -> u64;
}
unsafe extern "C" {
    pub fn wasm_runtime_module_free(module_inst: wasm_module_inst_t, ptr: u64);
}
unsafe extern "C" {
    pub fn wasm_runtime_module_dup_data(
        module_inst: wasm_module_inst_t,
        src: *const ::std::os::raw::c_char,
        size: u64,
    ) -> u64;
}
unsafe extern "C" {
    pub fn wasm_runtime_validate_app_addr(
        module_inst: wasm_module_inst_t,
        app_offset: u64,
        size: u64,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_validate_app_str_addr(
        module_inst: wasm_module_inst_t,
        app_str_offset: u64,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_validate_native_addr(
        module_inst: wasm_module_inst_t,
        native_ptr: *mut ::std::os::raw::c_void,
        size: u64,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_addr_app_to_native(
        module_inst: wasm_module_inst_t,
        app_offset: u64,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_addr_native_to_app(
        module_inst: wasm_module_inst_t,
        native_ptr: *mut ::std::os::raw::c_void,
    ) -> u64;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_app_addr_range(
        module_inst: wasm_module_inst_t,
        app_offset: u64,
        p_app_start_offset: *mut u64,
        p_app_end_offset: *mut u64,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_native_addr_range(
        module_inst: wasm_module_inst_t,
        native_ptr: *mut u8,
        p_native_start_addr: *mut *mut u8,
        p_native_end_addr: *mut *mut u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_import_count(module: wasm_module_t) -> i32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_import_type(
        module: wasm_module_t,
        import_index: i32,
        import_type: *mut wasm_import_t,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_get_export_count(module: wasm_module_t) -> i32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_export_type(
        module: wasm_module_t,
        export_index: i32,
        export_type: *mut wasm_export_t,
    );
}
unsafe extern "C" {
    pub fn wasm_func_type_get_param_count(func_type: wasm_func_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_func_type_get_param_valkind(
        func_type: wasm_func_type_t,
        param_index: u32,
    ) -> wasm_valkind_t;
}
unsafe extern "C" {
    pub fn wasm_func_type_get_result_count(func_type: wasm_func_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_func_type_get_result_valkind(
        func_type: wasm_func_type_t,
        result_index: u32,
    ) -> wasm_valkind_t;
}
unsafe extern "C" {
    pub fn wasm_global_type_get_valkind(global_type: wasm_global_type_t) -> wasm_valkind_t;
}
unsafe extern "C" {
    pub fn wasm_global_type_get_mutable(global_type: wasm_global_type_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_memory_type_get_shared(memory_type: wasm_memory_type_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_memory_type_get_init_page_count(memory_type: wasm_memory_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_memory_type_get_max_page_count(memory_type: wasm_memory_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_table_type_get_elem_kind(table_type: wasm_table_type_t) -> wasm_valkind_t;
}
unsafe extern "C" {
    pub fn wasm_table_type_get_shared(table_type: wasm_table_type_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_table_type_get_init_size(table_type: wasm_table_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_table_type_get_max_size(table_type: wasm_table_type_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_register_natives(
        module_name: *const ::std::os::raw::c_char,
        native_symbols: *mut NativeSymbol,
        n_native_symbols: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_register_natives_raw(
        module_name: *const ::std::os::raw::c_char,
        native_symbols: *mut NativeSymbol,
        n_native_symbols: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_unregister_natives(
        module_name: *const ::std::os::raw::c_char,
        native_symbols: *mut NativeSymbol,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_export_global_inst(
        module_inst: wasm_module_inst_t,
        name: *const ::std::os::raw::c_char,
        global_inst: *mut wasm_global_inst_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_export_table_inst(
        module_inst: wasm_module_inst_t,
        name: *const ::std::os::raw::c_char,
        table_inst: *mut wasm_table_inst_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_table_get_func_inst(
        module_inst: wasm_module_inst_t,
        table_inst: *const wasm_table_inst_t,
        idx: u32,
    ) -> wasm_function_inst_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_function_attachment(
        exec_env: wasm_exec_env_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_user_data(
        exec_env: wasm_exec_env_t,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_get_user_data(exec_env: wasm_exec_env_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_set_native_stack_boundary(
        exec_env: wasm_exec_env_t,
        native_stack_boundary: *mut u8,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_dump_mem_consumption(exec_env: wasm_exec_env_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_dump_perf_profiling(module_inst: wasm_module_inst_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_sum_wasm_exec_time(module_inst: wasm_module_inst_t) -> f64;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_wasm_func_exec_time(
        inst: wasm_module_inst_t,
        func_name: *const ::std::os::raw::c_char,
    ) -> f64;
}
pub type wasm_thread_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: wasm_exec_env_t,
        arg2: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type wasm_thread_t = usize;
unsafe extern "C" {
    pub fn wasm_runtime_set_max_thread_num(num: u32);
}
unsafe extern "C" {
    pub fn wasm_runtime_spawn_exec_env(exec_env: wasm_exec_env_t) -> wasm_exec_env_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_destroy_spawned_exec_env(exec_env: wasm_exec_env_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_spawn_thread(
        exec_env: wasm_exec_env_t,
        tid: *mut wasm_thread_t,
        callback: wasm_thread_callback_t,
        arg: *mut ::std::os::raw::c_void,
    ) -> i32;
}
unsafe extern "C" {
    pub fn wasm_runtime_join_thread(
        tid: wasm_thread_t,
        retval: *mut *mut ::std::os::raw::c_void,
    ) -> i32;
}
unsafe extern "C" {
    pub fn wasm_externref_obj2ref(
        module_inst: wasm_module_inst_t,
        extern_obj: *mut ::std::os::raw::c_void,
        p_externref_idx: *mut u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_externref_objdel(
        module_inst: wasm_module_inst_t,
        extern_obj: *mut ::std::os::raw::c_void,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_externref_set_cleanup(
        module_inst: wasm_module_inst_t,
        extern_obj: *mut ::std::os::raw::c_void,
        extern_obj_cleanup: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void),
        >,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_externref_ref2obj(
        externref_idx: u32,
        p_extern_obj: *mut *mut ::std::os::raw::c_void,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_externref_retain(externref_idx: u32) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_dump_call_stack(exec_env: wasm_exec_env_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_get_call_stack_buf_size(exec_env: wasm_exec_env_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_dump_call_stack_to_buf(
        exec_env: wasm_exec_env_t,
        buf: *mut ::std::os::raw::c_char,
        len: u32,
    ) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_pgo_prof_data_size(module_inst: wasm_module_inst_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_dump_pgo_prof_data_to_buf(
        module_inst: wasm_module_inst_t,
        buf: *mut ::std::os::raw::c_char,
        len: u32,
    ) -> u32;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_custom_section(
        module_comm: wasm_module_t,
        name: *const ::std::os::raw::c_char,
        len: *mut u32,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_version(major: *mut u32, minor: *mut u32, patch: *mut u32);
}
unsafe extern "C" {
    pub fn wasm_runtime_is_import_func_linked(
        module_name: *const ::std::os::raw::c_char,
        func_name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_is_import_global_linked(
        module_name: *const ::std::os::raw::c_char,
        global_name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_enlarge_memory(
        module_inst: wasm_module_inst_t,
        inc_page_count: u64,
    ) -> bool;
}
pub const enlarge_memory_error_reason_t_INTERNAL_ERROR: enlarge_memory_error_reason_t = 0;
pub const enlarge_memory_error_reason_t_MAX_SIZE_REACHED: enlarge_memory_error_reason_t = 1;
pub type enlarge_memory_error_reason_t = ::std::os::raw::c_uint;
pub type enlarge_memory_error_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        inc_page_count: u32,
        current_memory_size: u64,
        memory_index: u32,
        failure_reason: enlarge_memory_error_reason_t,
        instance: wasm_module_inst_t,
        exec_env: wasm_exec_env_t,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn wasm_runtime_set_enlarge_mem_error_callback(
        callback: enlarge_memory_error_callback_t,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_create_context_key(
        dtor: ::std::option::Option<
            unsafe extern "C" fn(inst: wasm_module_inst_t, ctx: *mut ::std::os::raw::c_void),
        >,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_destroy_context_key(key: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_runtime_set_context(
        inst: wasm_module_inst_t,
        key: *mut ::std::os::raw::c_void,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_set_context_spread(
        inst: wasm_module_inst_t,
        key: *mut ::std::os::raw::c_void,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wasm_runtime_get_context(
        inst: wasm_module_inst_t,
        key: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_runtime_begin_blocking_op(exec_env: wasm_exec_env_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_end_blocking_op(exec_env: wasm_exec_env_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_set_module_name(
        module: wasm_module_t,
        name: *const ::std::os::raw::c_char,
        error_buf: *mut ::std::os::raw::c_char,
        error_buf_size: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_get_module_name(module: wasm_module_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wasm_runtime_detect_native_stack_overflow(exec_env: wasm_exec_env_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_detect_native_stack_overflow_size(
        exec_env: wasm_exec_env_t,
        required_size: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_is_underlying_binary_freeable(module: wasm_module_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_create_shared_heap(
        init_args: *mut SharedHeapInitArgs,
    ) -> wasm_shared_heap_t;
}
unsafe extern "C" {
    pub fn wasm_runtime_attach_shared_heap(
        module_inst: wasm_module_inst_t,
        shared_heap: wasm_shared_heap_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_runtime_detach_shared_heap(module_inst: wasm_module_inst_t);
}
unsafe extern "C" {
    pub fn wasm_runtime_shared_heap_malloc(
        module_inst: wasm_module_inst_t,
        size: u64,
        p_native_addr: *mut *mut ::std::os::raw::c_void,
    ) -> u64;
}
unsafe extern "C" {
    pub fn wasm_runtime_shared_heap_free(module_inst: wasm_module_inst_t, ptr: u64);
}
pub type byte_t = ::std::os::raw::c_char;
pub type wasm_byte_t = byte_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_byte_vec_t {
    pub size: usize,
    pub data: *mut wasm_byte_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_byte_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_byte_vec_new_empty(out: *mut wasm_byte_vec_t);
}
unsafe extern "C" {
    pub fn wasm_byte_vec_new_uninitialized(out: *mut wasm_byte_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_byte_vec_new(out: *mut wasm_byte_vec_t, arg1: usize, arg2: *const wasm_byte_t);
}
unsafe extern "C" {
    pub fn wasm_byte_vec_copy(out: *mut wasm_byte_vec_t, arg1: *const wasm_byte_vec_t);
}
unsafe extern "C" {
    pub fn wasm_byte_vec_delete(arg1: *mut wasm_byte_vec_t);
}
pub type wasm_name_t = wasm_byte_vec_t;
unsafe extern "C" {
    pub fn wasm_config_delete(arg1: *mut wasm_config_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_config_t {
    pub mem_alloc_type: mem_alloc_type_t,
    pub mem_alloc_option: MemAllocOption,
    pub segue_flags: u32,
    pub enable_linux_perf: bool,
}
impl Default for wasm_config_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_config_new() -> *mut wasm_config_t;
}
unsafe extern "C" {
    pub fn wasm_config_set_mem_alloc_opt(
        arg1: *mut wasm_config_t,
        arg2: mem_alloc_type_t,
        arg3: *mut MemAllocOption,
    ) -> *mut wasm_config_t;
}
unsafe extern "C" {
    pub fn wasm_config_set_linux_perf_opt(
        arg1: *mut wasm_config_t,
        arg2: bool,
    ) -> *mut wasm_config_t;
}
unsafe extern "C" {
    pub fn wasm_config_set_segue_flags(
        config: *mut wasm_config_t,
        segue_flags: u32,
    ) -> *mut wasm_config_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_engine_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_engine_delete(arg1: *mut wasm_engine_t);
}
unsafe extern "C" {
    pub fn wasm_engine_new() -> *mut wasm_engine_t;
}
unsafe extern "C" {
    pub fn wasm_engine_new_with_config(arg1: *mut wasm_config_t) -> *mut wasm_engine_t;
}
unsafe extern "C" {
    pub fn wasm_engine_new_with_args(
        type_: mem_alloc_type_t,
        opts: *const MemAllocOption,
    ) -> *mut wasm_engine_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_store_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_store_delete(arg1: *mut wasm_store_t);
}
unsafe extern "C" {
    pub fn wasm_store_new(arg1: *mut wasm_engine_t) -> *mut wasm_store_t;
}
pub type wasm_mutability_t = u8;
pub const wasm_mutability_enum_WASM_CONST: wasm_mutability_enum = 0;
pub const wasm_mutability_enum_WASM_VAR: wasm_mutability_enum = 1;
pub type wasm_mutability_enum = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct wasm_limits_t {
    pub min: u32,
    pub max: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_valtype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_valtype_delete(arg1: *mut wasm_valtype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_valtype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_valtype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_valtype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_valtype_vec_new_empty(out: *mut wasm_valtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_valtype_vec_new_uninitialized(out: *mut wasm_valtype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_valtype_vec_new(
        out: *mut wasm_valtype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_valtype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_valtype_vec_copy(out: *mut wasm_valtype_vec_t, arg1: *const wasm_valtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_valtype_vec_delete(arg1: *mut wasm_valtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_valtype_copy(arg1: *const wasm_valtype_t) -> *mut wasm_valtype_t;
}
unsafe extern "C" {
    pub fn wasm_valtype_new(arg1: wasm_valkind_t) -> *mut wasm_valtype_t;
}
unsafe extern "C" {
    pub fn wasm_valtype_kind(arg1: *const wasm_valtype_t) -> wasm_valkind_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_functype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_functype_delete(arg1: *mut wasm_functype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_functype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_functype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_functype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_functype_vec_new_empty(out: *mut wasm_functype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_functype_vec_new_uninitialized(out: *mut wasm_functype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_functype_vec_new(
        out: *mut wasm_functype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_functype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_functype_vec_copy(out: *mut wasm_functype_vec_t, arg1: *const wasm_functype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_functype_vec_delete(arg1: *mut wasm_functype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_functype_copy(arg1: *const wasm_functype_t) -> *mut wasm_functype_t;
}
unsafe extern "C" {
    pub fn wasm_functype_new(
        params: *mut wasm_valtype_vec_t,
        results: *mut wasm_valtype_vec_t,
    ) -> *mut wasm_functype_t;
}
unsafe extern "C" {
    pub fn wasm_functype_params(arg1: *const wasm_functype_t) -> *const wasm_valtype_vec_t;
}
unsafe extern "C" {
    pub fn wasm_functype_results(arg1: *const wasm_functype_t) -> *const wasm_valtype_vec_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_globaltype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_globaltype_delete(arg1: *mut wasm_globaltype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_globaltype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_globaltype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_globaltype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_globaltype_vec_new_empty(out: *mut wasm_globaltype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_globaltype_vec_new_uninitialized(out: *mut wasm_globaltype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_globaltype_vec_new(
        out: *mut wasm_globaltype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_globaltype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_globaltype_vec_copy(
        out: *mut wasm_globaltype_vec_t,
        arg1: *const wasm_globaltype_vec_t,
    );
}
unsafe extern "C" {
    pub fn wasm_globaltype_vec_delete(arg1: *mut wasm_globaltype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_globaltype_copy(arg1: *const wasm_globaltype_t) -> *mut wasm_globaltype_t;
}
unsafe extern "C" {
    pub fn wasm_globaltype_new(
        arg1: *mut wasm_valtype_t,
        arg2: wasm_mutability_t,
    ) -> *mut wasm_globaltype_t;
}
unsafe extern "C" {
    pub fn wasm_globaltype_content(arg1: *const wasm_globaltype_t) -> *const wasm_valtype_t;
}
unsafe extern "C" {
    pub fn wasm_globaltype_mutability(arg1: *const wasm_globaltype_t) -> wasm_mutability_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_tabletype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_tabletype_delete(arg1: *mut wasm_tabletype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_tabletype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_tabletype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_tabletype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_tabletype_vec_new_empty(out: *mut wasm_tabletype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_tabletype_vec_new_uninitialized(out: *mut wasm_tabletype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_tabletype_vec_new(
        out: *mut wasm_tabletype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_tabletype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_tabletype_vec_copy(
        out: *mut wasm_tabletype_vec_t,
        arg1: *const wasm_tabletype_vec_t,
    );
}
unsafe extern "C" {
    pub fn wasm_tabletype_vec_delete(arg1: *mut wasm_tabletype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_tabletype_copy(arg1: *const wasm_tabletype_t) -> *mut wasm_tabletype_t;
}
unsafe extern "C" {
    pub fn wasm_tabletype_new(
        arg1: *mut wasm_valtype_t,
        arg2: *const wasm_limits_t,
    ) -> *mut wasm_tabletype_t;
}
unsafe extern "C" {
    pub fn wasm_tabletype_element(arg1: *const wasm_tabletype_t) -> *const wasm_valtype_t;
}
unsafe extern "C" {
    pub fn wasm_tabletype_limits(arg1: *const wasm_tabletype_t) -> *const wasm_limits_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_memorytype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_memorytype_delete(arg1: *mut wasm_memorytype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_memorytype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_memorytype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_memorytype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_memorytype_vec_new_empty(out: *mut wasm_memorytype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_memorytype_vec_new_uninitialized(out: *mut wasm_memorytype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_memorytype_vec_new(
        out: *mut wasm_memorytype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_memorytype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_memorytype_vec_copy(
        out: *mut wasm_memorytype_vec_t,
        arg1: *const wasm_memorytype_vec_t,
    );
}
unsafe extern "C" {
    pub fn wasm_memorytype_vec_delete(arg1: *mut wasm_memorytype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_memorytype_copy(arg1: *const wasm_memorytype_t) -> *mut wasm_memorytype_t;
}
unsafe extern "C" {
    pub fn wasm_memorytype_new(arg1: *const wasm_limits_t) -> *mut wasm_memorytype_t;
}
unsafe extern "C" {
    pub fn wasm_memorytype_limits(arg1: *const wasm_memorytype_t) -> *const wasm_limits_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_externtype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_externtype_delete(arg1: *mut wasm_externtype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_externtype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_externtype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_externtype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_externtype_vec_new_empty(out: *mut wasm_externtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_externtype_vec_new_uninitialized(out: *mut wasm_externtype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_externtype_vec_new(
        out: *mut wasm_externtype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_externtype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_externtype_vec_copy(
        out: *mut wasm_externtype_vec_t,
        arg1: *const wasm_externtype_vec_t,
    );
}
unsafe extern "C" {
    pub fn wasm_externtype_vec_delete(arg1: *mut wasm_externtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_externtype_copy(arg1: *const wasm_externtype_t) -> *mut wasm_externtype_t;
}
pub type wasm_externkind_t = u8;
pub const wasm_externkind_enum_WASM_EXTERN_FUNC: wasm_externkind_enum = 0;
pub const wasm_externkind_enum_WASM_EXTERN_GLOBAL: wasm_externkind_enum = 1;
pub const wasm_externkind_enum_WASM_EXTERN_TABLE: wasm_externkind_enum = 2;
pub const wasm_externkind_enum_WASM_EXTERN_MEMORY: wasm_externkind_enum = 3;
pub type wasm_externkind_enum = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wasm_externtype_kind(arg1: *const wasm_externtype_t) -> wasm_externkind_t;
}
unsafe extern "C" {
    pub fn wasm_functype_as_externtype(arg1: *mut wasm_functype_t) -> *mut wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_globaltype_as_externtype(arg1: *mut wasm_globaltype_t) -> *mut wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_tabletype_as_externtype(arg1: *mut wasm_tabletype_t) -> *mut wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_memorytype_as_externtype(arg1: *mut wasm_memorytype_t) -> *mut wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_functype(arg1: *mut wasm_externtype_t) -> *mut wasm_functype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_globaltype(arg1: *mut wasm_externtype_t) -> *mut wasm_globaltype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_tabletype(arg1: *mut wasm_externtype_t) -> *mut wasm_tabletype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_memorytype(arg1: *mut wasm_externtype_t) -> *mut wasm_memorytype_t;
}
unsafe extern "C" {
    pub fn wasm_functype_as_externtype_const(
        arg1: *const wasm_functype_t,
    ) -> *const wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_globaltype_as_externtype_const(
        arg1: *const wasm_globaltype_t,
    ) -> *const wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_tabletype_as_externtype_const(
        arg1: *const wasm_tabletype_t,
    ) -> *const wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_memorytype_as_externtype_const(
        arg1: *const wasm_memorytype_t,
    ) -> *const wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_functype_const(
        arg1: *const wasm_externtype_t,
    ) -> *const wasm_functype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_globaltype_const(
        arg1: *const wasm_externtype_t,
    ) -> *const wasm_globaltype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_tabletype_const(
        arg1: *const wasm_externtype_t,
    ) -> *const wasm_tabletype_t;
}
unsafe extern "C" {
    pub fn wasm_externtype_as_memorytype_const(
        arg1: *const wasm_externtype_t,
    ) -> *const wasm_memorytype_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_importtype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_importtype_delete(arg1: *mut wasm_importtype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_importtype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_importtype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_importtype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_importtype_vec_new_empty(out: *mut wasm_importtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_importtype_vec_new_uninitialized(out: *mut wasm_importtype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_importtype_vec_new(
        out: *mut wasm_importtype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_importtype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_importtype_vec_copy(
        out: *mut wasm_importtype_vec_t,
        arg1: *const wasm_importtype_vec_t,
    );
}
unsafe extern "C" {
    pub fn wasm_importtype_vec_delete(arg1: *mut wasm_importtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_importtype_copy(arg1: *const wasm_importtype_t) -> *mut wasm_importtype_t;
}
unsafe extern "C" {
    pub fn wasm_importtype_new(
        module: *mut wasm_name_t,
        name: *mut wasm_name_t,
        arg1: *mut wasm_externtype_t,
    ) -> *mut wasm_importtype_t;
}
unsafe extern "C" {
    pub fn wasm_importtype_module(arg1: *const wasm_importtype_t) -> *const wasm_name_t;
}
unsafe extern "C" {
    pub fn wasm_importtype_name(arg1: *const wasm_importtype_t) -> *const wasm_name_t;
}
unsafe extern "C" {
    pub fn wasm_importtype_type(arg1: *const wasm_importtype_t) -> *const wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_importtype_is_linked(arg1: *const wasm_importtype_t) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_exporttype_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_exporttype_delete(arg1: *mut wasm_exporttype_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_exporttype_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_exporttype_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_exporttype_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_exporttype_vec_new_empty(out: *mut wasm_exporttype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_exporttype_vec_new_uninitialized(out: *mut wasm_exporttype_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_exporttype_vec_new(
        out: *mut wasm_exporttype_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_exporttype_t,
    );
}
unsafe extern "C" {
    pub fn wasm_exporttype_vec_copy(
        out: *mut wasm_exporttype_vec_t,
        arg1: *const wasm_exporttype_vec_t,
    );
}
unsafe extern "C" {
    pub fn wasm_exporttype_vec_delete(arg1: *mut wasm_exporttype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_exporttype_copy(arg1: *const wasm_exporttype_t) -> *mut wasm_exporttype_t;
}
unsafe extern "C" {
    pub fn wasm_exporttype_new(
        arg1: *mut wasm_name_t,
        arg2: *mut wasm_externtype_t,
    ) -> *mut wasm_exporttype_t;
}
unsafe extern "C" {
    pub fn wasm_exporttype_name(arg1: *const wasm_exporttype_t) -> *const wasm_name_t;
}
unsafe extern "C" {
    pub fn wasm_exporttype_type(arg1: *const wasm_exporttype_t) -> *const wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_val_delete(v: *mut wasm_val_t);
}
unsafe extern "C" {
    pub fn wasm_val_copy(out: *mut wasm_val_t, arg1: *const wasm_val_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_val_vec_t {
    pub size: usize,
    pub data: *mut wasm_val_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_val_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_val_vec_new_empty(out: *mut wasm_val_vec_t);
}
unsafe extern "C" {
    pub fn wasm_val_vec_new_uninitialized(out: *mut wasm_val_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_val_vec_new(out: *mut wasm_val_vec_t, arg1: usize, arg2: *const wasm_val_t);
}
unsafe extern "C" {
    pub fn wasm_val_vec_copy(out: *mut wasm_val_vec_t, arg1: *const wasm_val_vec_t);
}
unsafe extern "C" {
    pub fn wasm_val_vec_delete(arg1: *mut wasm_val_vec_t);
}
unsafe extern "C" {
    pub fn wasm_ref_delete(arg1: *mut wasm_ref_t);
}
unsafe extern "C" {
    pub fn wasm_ref_copy(arg1: *const wasm_ref_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_same(arg1: *const wasm_ref_t, arg2: *const wasm_ref_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_ref_get_host_info(arg1: *const wasm_ref_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_ref_set_host_info(arg1: *mut wasm_ref_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_ref_set_host_info_with_finalizer(
        arg1: *mut wasm_ref_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_frame_delete(arg1: *mut wasm_frame_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_frame_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_frame_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_frame_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_frame_vec_new_empty(out: *mut wasm_frame_vec_t);
}
unsafe extern "C" {
    pub fn wasm_frame_vec_new_uninitialized(out: *mut wasm_frame_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_frame_vec_new(
        out: *mut wasm_frame_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_frame_t,
    );
}
unsafe extern "C" {
    pub fn wasm_frame_vec_copy(out: *mut wasm_frame_vec_t, arg1: *const wasm_frame_vec_t);
}
unsafe extern "C" {
    pub fn wasm_frame_vec_delete(arg1: *mut wasm_frame_vec_t);
}
unsafe extern "C" {
    pub fn wasm_frame_copy(arg1: *const wasm_frame_t) -> *mut wasm_frame_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_instance_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_frame_instance(arg1: *const wasm_frame_t) -> *mut wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_frame_func_index(arg1: *const wasm_frame_t) -> u32;
}
unsafe extern "C" {
    pub fn wasm_frame_func_offset(arg1: *const wasm_frame_t) -> usize;
}
unsafe extern "C" {
    pub fn wasm_frame_module_offset(arg1: *const wasm_frame_t) -> usize;
}
pub type wasm_message_t = wasm_name_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_trap_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_trap_delete(arg1: *mut wasm_trap_t);
}
unsafe extern "C" {
    pub fn wasm_trap_copy(arg1: *const wasm_trap_t) -> *mut wasm_trap_t;
}
unsafe extern "C" {
    pub fn wasm_trap_same(arg1: *const wasm_trap_t, arg2: *const wasm_trap_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_trap_get_host_info(arg1: *const wasm_trap_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_trap_set_host_info(arg1: *mut wasm_trap_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_trap_set_host_info_with_finalizer(
        arg1: *mut wasm_trap_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_trap_as_ref(arg1: *mut wasm_trap_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_trap(arg1: *mut wasm_ref_t) -> *mut wasm_trap_t;
}
unsafe extern "C" {
    pub fn wasm_trap_as_ref_const(arg1: *const wasm_trap_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_trap_const(arg1: *const wasm_ref_t) -> *const wasm_trap_t;
}
unsafe extern "C" {
    pub fn wasm_trap_new(store: *mut wasm_store_t, arg1: *const wasm_message_t)
    -> *mut wasm_trap_t;
}
unsafe extern "C" {
    pub fn wasm_trap_message(arg1: *const wasm_trap_t, out: *mut wasm_message_t);
}
unsafe extern "C" {
    pub fn wasm_trap_origin(arg1: *const wasm_trap_t) -> *mut wasm_frame_t;
}
unsafe extern "C" {
    pub fn wasm_trap_trace(arg1: *const wasm_trap_t, out: *mut wasm_frame_vec_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_foreign_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_foreign_delete(arg1: *mut wasm_foreign_t);
}
unsafe extern "C" {
    pub fn wasm_foreign_copy(arg1: *const wasm_foreign_t) -> *mut wasm_foreign_t;
}
unsafe extern "C" {
    pub fn wasm_foreign_same(arg1: *const wasm_foreign_t, arg2: *const wasm_foreign_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_foreign_get_host_info(arg1: *const wasm_foreign_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_foreign_set_host_info(arg1: *mut wasm_foreign_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_foreign_set_host_info_with_finalizer(
        arg1: *mut wasm_foreign_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_foreign_as_ref(arg1: *mut wasm_foreign_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_foreign(arg1: *mut wasm_ref_t) -> *mut wasm_foreign_t;
}
unsafe extern "C" {
    pub fn wasm_foreign_as_ref_const(arg1: *const wasm_foreign_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_foreign_const(arg1: *const wasm_ref_t) -> *const wasm_foreign_t;
}
unsafe extern "C" {
    pub fn wasm_foreign_new(arg1: *mut wasm_store_t) -> *mut wasm_foreign_t;
}
unsafe extern "C" {
    pub fn wasm_module_new(
        arg1: *mut wasm_store_t,
        binary: *const wasm_byte_vec_t,
    ) -> *mut wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_module_new_ex(
        arg1: *mut wasm_store_t,
        binary: *mut wasm_byte_vec_t,
        args: *mut LoadArgs,
    ) -> *mut wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_module_delete(arg1: *mut wasm_module_t);
}
unsafe extern "C" {
    pub fn wasm_module_validate(arg1: *mut wasm_store_t, binary: *const wasm_byte_vec_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_module_imports(arg1: *const wasm_module_t, out: *mut wasm_importtype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_module_exports(arg1: *const wasm_module_t, out: *mut wasm_exporttype_vec_t);
}
unsafe extern "C" {
    pub fn wasm_module_serialize(arg1: *mut wasm_module_t, out: *mut wasm_byte_vec_t);
}
unsafe extern "C" {
    pub fn wasm_module_deserialize(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_byte_vec_t,
    ) -> *mut wasm_module_t;
}
pub type wasm_shared_module_t = wasm_module_t;
unsafe extern "C" {
    pub fn wasm_module_share(arg1: *mut wasm_module_t) -> *mut wasm_shared_module_t;
}
unsafe extern "C" {
    pub fn wasm_module_obtain(
        arg1: *mut wasm_store_t,
        arg2: *mut wasm_shared_module_t,
    ) -> *mut wasm_module_t;
}
unsafe extern "C" {
    pub fn wasm_shared_module_delete(arg1: *mut wasm_shared_module_t);
}
unsafe extern "C" {
    pub fn wasm_module_set_name(
        arg1: *mut wasm_module_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_module_get_name(arg1: *mut wasm_module_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wasm_module_is_underlying_binary_freeable(module: *const wasm_module_t) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_func_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_func_delete(arg1: *mut wasm_func_t);
}
unsafe extern "C" {
    pub fn wasm_func_copy(arg1: *const wasm_func_t) -> *mut wasm_func_t;
}
unsafe extern "C" {
    pub fn wasm_func_same(arg1: *const wasm_func_t, arg2: *const wasm_func_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_func_get_host_info(arg1: *const wasm_func_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_func_set_host_info(arg1: *mut wasm_func_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_func_set_host_info_with_finalizer(
        arg1: *mut wasm_func_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_func_as_ref(arg1: *mut wasm_func_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_func(arg1: *mut wasm_ref_t) -> *mut wasm_func_t;
}
unsafe extern "C" {
    pub fn wasm_func_as_ref_const(arg1: *const wasm_func_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_func_const(arg1: *const wasm_ref_t) -> *const wasm_func_t;
}
pub type wasm_func_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        args: *const wasm_val_vec_t,
        results: *mut wasm_val_vec_t,
    ) -> *mut wasm_trap_t,
>;
pub type wasm_func_callback_with_env_t = ::std::option::Option<
    unsafe extern "C" fn(
        env: *mut ::std::os::raw::c_void,
        args: *const wasm_val_vec_t,
        results: *mut wasm_val_vec_t,
    ) -> *mut wasm_trap_t,
>;
unsafe extern "C" {
    pub fn wasm_func_new(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_functype_t,
        arg3: wasm_func_callback_t,
    ) -> *mut wasm_func_t;
}
unsafe extern "C" {
    pub fn wasm_func_new_with_env(
        arg1: *mut wasm_store_t,
        type_: *const wasm_functype_t,
        arg2: wasm_func_callback_with_env_t,
        env: *mut ::std::os::raw::c_void,
        finalizer: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> *mut wasm_func_t;
}
unsafe extern "C" {
    pub fn wasm_func_type(arg1: *const wasm_func_t) -> *mut wasm_functype_t;
}
unsafe extern "C" {
    pub fn wasm_func_param_arity(arg1: *const wasm_func_t) -> usize;
}
unsafe extern "C" {
    pub fn wasm_func_result_arity(arg1: *const wasm_func_t) -> usize;
}
unsafe extern "C" {
    pub fn wasm_func_call(
        arg1: *const wasm_func_t,
        args: *const wasm_val_vec_t,
        results: *mut wasm_val_vec_t,
    ) -> *mut wasm_trap_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_global_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_global_delete(arg1: *mut wasm_global_t);
}
unsafe extern "C" {
    pub fn wasm_global_copy(arg1: *const wasm_global_t) -> *mut wasm_global_t;
}
unsafe extern "C" {
    pub fn wasm_global_same(arg1: *const wasm_global_t, arg2: *const wasm_global_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_global_get_host_info(arg1: *const wasm_global_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_global_set_host_info(arg1: *mut wasm_global_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_global_set_host_info_with_finalizer(
        arg1: *mut wasm_global_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_global_as_ref(arg1: *mut wasm_global_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_global(arg1: *mut wasm_ref_t) -> *mut wasm_global_t;
}
unsafe extern "C" {
    pub fn wasm_global_as_ref_const(arg1: *const wasm_global_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_global_const(arg1: *const wasm_ref_t) -> *const wasm_global_t;
}
unsafe extern "C" {
    pub fn wasm_global_new(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_globaltype_t,
        arg3: *const wasm_val_t,
    ) -> *mut wasm_global_t;
}
unsafe extern "C" {
    pub fn wasm_global_type(arg1: *const wasm_global_t) -> *mut wasm_globaltype_t;
}
unsafe extern "C" {
    pub fn wasm_global_get(arg1: *const wasm_global_t, out: *mut wasm_val_t);
}
unsafe extern "C" {
    pub fn wasm_global_set(arg1: *mut wasm_global_t, arg2: *const wasm_val_t);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_table_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_table_delete(arg1: *mut wasm_table_t);
}
unsafe extern "C" {
    pub fn wasm_table_copy(arg1: *const wasm_table_t) -> *mut wasm_table_t;
}
unsafe extern "C" {
    pub fn wasm_table_same(arg1: *const wasm_table_t, arg2: *const wasm_table_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_table_get_host_info(arg1: *const wasm_table_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_table_set_host_info(arg1: *mut wasm_table_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_table_set_host_info_with_finalizer(
        arg1: *mut wasm_table_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_table_as_ref(arg1: *mut wasm_table_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_table(arg1: *mut wasm_ref_t) -> *mut wasm_table_t;
}
unsafe extern "C" {
    pub fn wasm_table_as_ref_const(arg1: *const wasm_table_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_table_const(arg1: *const wasm_ref_t) -> *const wasm_table_t;
}
pub type wasm_table_size_t = u32;
unsafe extern "C" {
    pub fn wasm_table_new(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_tabletype_t,
        init: *mut wasm_ref_t,
    ) -> *mut wasm_table_t;
}
unsafe extern "C" {
    pub fn wasm_table_type(arg1: *const wasm_table_t) -> *mut wasm_tabletype_t;
}
unsafe extern "C" {
    pub fn wasm_table_get(arg1: *const wasm_table_t, index: wasm_table_size_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_table_set(
        arg1: *mut wasm_table_t,
        index: wasm_table_size_t,
        arg2: *mut wasm_ref_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn wasm_table_size(arg1: *const wasm_table_t) -> wasm_table_size_t;
}
unsafe extern "C" {
    pub fn wasm_table_grow(
        arg1: *mut wasm_table_t,
        delta: wasm_table_size_t,
        init: *mut wasm_ref_t,
    ) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_memory_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_memory_delete(arg1: *mut wasm_memory_t);
}
unsafe extern "C" {
    pub fn wasm_memory_copy(arg1: *const wasm_memory_t) -> *mut wasm_memory_t;
}
unsafe extern "C" {
    pub fn wasm_memory_same(arg1: *const wasm_memory_t, arg2: *const wasm_memory_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_memory_get_host_info(arg1: *const wasm_memory_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_memory_set_host_info(arg1: *mut wasm_memory_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_memory_set_host_info_with_finalizer(
        arg1: *mut wasm_memory_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_memory_as_ref(arg1: *mut wasm_memory_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_memory(arg1: *mut wasm_ref_t) -> *mut wasm_memory_t;
}
unsafe extern "C" {
    pub fn wasm_memory_as_ref_const(arg1: *const wasm_memory_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_memory_const(arg1: *const wasm_ref_t) -> *const wasm_memory_t;
}
pub type wasm_memory_pages_t = u32;
unsafe extern "C" {
    pub fn wasm_memory_new(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_memorytype_t,
    ) -> *mut wasm_memory_t;
}
unsafe extern "C" {
    pub fn wasm_memory_type(arg1: *const wasm_memory_t) -> *mut wasm_memorytype_t;
}
unsafe extern "C" {
    pub fn wasm_memory_data(arg1: *mut wasm_memory_t) -> *mut byte_t;
}
unsafe extern "C" {
    pub fn wasm_memory_data_size(arg1: *const wasm_memory_t) -> usize;
}
unsafe extern "C" {
    pub fn wasm_memory_size(arg1: *const wasm_memory_t) -> wasm_memory_pages_t;
}
unsafe extern "C" {
    pub fn wasm_memory_grow(arg1: *mut wasm_memory_t, delta: wasm_memory_pages_t) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_extern_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn wasm_extern_delete(arg1: *mut wasm_extern_t);
}
unsafe extern "C" {
    pub fn wasm_extern_copy(arg1: *const wasm_extern_t) -> *mut wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_extern_same(arg1: *const wasm_extern_t, arg2: *const wasm_extern_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_extern_get_host_info(arg1: *const wasm_extern_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_extern_set_host_info(arg1: *mut wasm_extern_t, arg2: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wasm_extern_set_host_info_with_finalizer(
        arg1: *mut wasm_extern_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_extern_as_ref(arg1: *mut wasm_extern_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_extern(arg1: *mut wasm_ref_t) -> *mut wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_ref_const(arg1: *const wasm_extern_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_extern_const(arg1: *const wasm_ref_t) -> *const wasm_extern_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wasm_extern_vec_t {
    pub size: usize,
    pub data: *mut *mut wasm_extern_t,
    pub num_elems: usize,
    pub size_of_elem: usize,
    pub lock: *mut ::std::os::raw::c_void,
}
impl Default for wasm_extern_vec_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn wasm_extern_vec_new_empty(out: *mut wasm_extern_vec_t);
}
unsafe extern "C" {
    pub fn wasm_extern_vec_new_uninitialized(out: *mut wasm_extern_vec_t, arg1: usize);
}
unsafe extern "C" {
    pub fn wasm_extern_vec_new(
        out: *mut wasm_extern_vec_t,
        arg1: usize,
        arg2: *const *mut wasm_extern_t,
    );
}
unsafe extern "C" {
    pub fn wasm_extern_vec_copy(out: *mut wasm_extern_vec_t, arg1: *const wasm_extern_vec_t);
}
unsafe extern "C" {
    pub fn wasm_extern_vec_delete(arg1: *mut wasm_extern_vec_t);
}
unsafe extern "C" {
    pub fn wasm_extern_kind(arg1: *const wasm_extern_t) -> wasm_externkind_t;
}
unsafe extern "C" {
    pub fn wasm_extern_type(arg1: *const wasm_extern_t) -> *mut wasm_externtype_t;
}
unsafe extern "C" {
    pub fn wasm_func_as_extern(arg1: *mut wasm_func_t) -> *mut wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_global_as_extern(arg1: *mut wasm_global_t) -> *mut wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_table_as_extern(arg1: *mut wasm_table_t) -> *mut wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_memory_as_extern(arg1: *mut wasm_memory_t) -> *mut wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_func(arg1: *mut wasm_extern_t) -> *mut wasm_func_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_global(arg1: *mut wasm_extern_t) -> *mut wasm_global_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_table(arg1: *mut wasm_extern_t) -> *mut wasm_table_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_memory(arg1: *mut wasm_extern_t) -> *mut wasm_memory_t;
}
unsafe extern "C" {
    pub fn wasm_func_as_extern_const(arg1: *const wasm_func_t) -> *const wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_global_as_extern_const(arg1: *const wasm_global_t) -> *const wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_table_as_extern_const(arg1: *const wasm_table_t) -> *const wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_memory_as_extern_const(arg1: *const wasm_memory_t) -> *const wasm_extern_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_func_const(arg1: *const wasm_extern_t) -> *const wasm_func_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_global_const(arg1: *const wasm_extern_t) -> *const wasm_global_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_table_const(arg1: *const wasm_extern_t) -> *const wasm_table_t;
}
unsafe extern "C" {
    pub fn wasm_extern_as_memory_const(arg1: *const wasm_extern_t) -> *const wasm_memory_t;
}
unsafe extern "C" {
    pub fn wasm_instance_delete(arg1: *mut wasm_instance_t);
}
unsafe extern "C" {
    pub fn wasm_instance_copy(arg1: *const wasm_instance_t) -> *mut wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_instance_same(arg1: *const wasm_instance_t, arg2: *const wasm_instance_t) -> bool;
}
unsafe extern "C" {
    pub fn wasm_instance_get_host_info(arg1: *const wasm_instance_t)
    -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wasm_instance_set_host_info(
        arg1: *mut wasm_instance_t,
        arg2: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wasm_instance_set_host_info_with_finalizer(
        arg1: *mut wasm_instance_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    );
}
unsafe extern "C" {
    pub fn wasm_instance_as_ref(arg1: *mut wasm_instance_t) -> *mut wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_instance(arg1: *mut wasm_ref_t) -> *mut wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_instance_as_ref_const(arg1: *const wasm_instance_t) -> *const wasm_ref_t;
}
unsafe extern "C" {
    pub fn wasm_ref_as_instance_const(arg1: *const wasm_ref_t) -> *const wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_instance_new(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_module_t,
        imports: *const wasm_extern_vec_t,
        trap: *mut *mut wasm_trap_t,
    ) -> *mut wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_instance_new_with_args(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_module_t,
        imports: *const wasm_extern_vec_t,
        trap: *mut *mut wasm_trap_t,
        stack_size: u32,
        heap_size: u32,
    ) -> *mut wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_instance_new_with_args_ex(
        arg1: *mut wasm_store_t,
        arg2: *const wasm_module_t,
        imports: *const wasm_extern_vec_t,
        trap: *mut *mut wasm_trap_t,
        inst_args: *const InstantiationArgs,
    ) -> *mut wasm_instance_t;
}
unsafe extern "C" {
    pub fn wasm_instance_exports(arg1: *const wasm_instance_t, out: *mut wasm_extern_vec_t);
}
unsafe extern "C" {
    pub fn wasm_instance_sum_wasm_exec_time(arg1: *const wasm_instance_t) -> f64;
}
unsafe extern "C" {
    pub fn wasm_instance_get_wasm_func_exec_time(
        arg1: *const wasm_instance_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> f64;
}
unsafe extern "C" {
    pub fn wasm_extern_new_empty(
        arg1: *mut wasm_store_t,
        arg2: wasm_externkind_t,
    ) -> *mut wasm_extern_t;
}
